### ISSUE TITLE
PHP notice in handle_donation_status_change() method

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#100]
>[18-Feb-2016 18:55:55 UTC] PHP Notice:  Undefined index: new in D:\Websites\www.sandbox.dev\wp-content\plugins\charitable\includes\admin\donations\class-charitable-donation-post-type.php on line 143

Then the donation log is updated with 

>Donation status updated from to Pending.

This can be traced to the donation processor inserting the new donation post and running [`wp_transition_post_status()`](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3400) on the new post. If you trace back a bit you see that the `$previous_status` on a new post is `new`, which is the index being sought in the notice. 

Is there a need to have the initial pending status logged? If so, could that be logged in the "Donation created" first log update? Or could we just use a bit of conditional logic so that the message is 

>Donation status set to Pending.

on a new post?

**Comment by helgatheviking** [comment]
I see you are up and at it today. thanks for getting this merged in.

**Comment by ericnicolaas** [comment]
@helgatheviking No problem. Kicking myself for some of the errors in 1.3!

**Comment by helgatheviking** [comment]
It happens. I tried to add fancier error notices to one of my plugins and it resulted in 500 errors for people! I'm sure you'll get a 1.3.1 fix out soon enough.
