### ISSUE TITLE
The link you have used to enter the PayPal system contains an incorrectly formatted item amount.

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#102]
Something has changed in the [paypal args](https://github.com/Charitable/Charitable/blob/master/includes/gateways/class-charitable-gateway-paypal.php#L141) such that `$donation->get_total_donation_amount()` is returning a value such as 10.000 which is not acceptable to PayPal. I'm still thinking that the total should be a meta value for the donation post, but while I was working on that I came across this. At first I thought it was all the stuff I am monkeying around with,  but I tested it on a separate site with just the .org version (only lightly patched for that `die()` issue I mentioned in #99

**Comment by ericnicolaas** [comment]
@helgatheviking 7bd6d1a656b920840d175896c97b89d66d586427 should fix this. The problem is that I shifted from a FLOAT column to a DECIMAL column for the amount values, with 4 decimal places -- which screws up PayPal.

**Comment by helgatheviking** [comment]
Yes, it was 4 decimals that was messing things up. PayPal apparently needs 2 decimal places and point decimals.

**Comment by ericnicolaas** [comment]
OK, this is closed. Version 1.3.1 is going up.
