### ISSUE TITLE
Refactor save_donation() method to standalone function

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#109]
It'd be great to move most of the `save_donation()` method from the processor class to a function such as `charitable_create_donation()`. Then it would be possible to add orders programmatically... especially helpful when creating new donations for each recurrence in recurring donations.

**Comment by ericnicolaas** [comment]
I agree that it needs to be easier to add orders programatically, but I'm not sure a function is the best approach. My preference would be to move `Charitable_Donation_Processor` away from being a singleton class, so that it can be instantiated multiple times without issues. 

For now, a really basic way to achieve it is with this:

```
$donation_id = Charitable_Donation_Processor::get_instance()->save_donation( $args );
Charitable_Donation_Processor::destroy();
```

**Comment by helgatheviking** [comment]
For reference, my inspiration was [`wc_create_order()`](https://github.com/woothemes/woocommerce/blob/f52b01827998198582983da56cdfdc402c238869/includes/wc-core-functions.php#L59).

**Comment by ericnicolaas** [comment]
In theory, `charitable_create_donation` could be as simple as this:

```
function charitable_create_donation( $args ) {
    $donation_id = Charitable_Donation_Processor::get_instance()->save_donation( $args );
    Charitable_Donation_Processor::destroy();
}
```

**Comment by helgatheviking** [comment]
Technically, I guess that *could* work, though you currently can't pass any meta fields through the `$args`.

**Comment by ericnicolaas** [comment]
@helgatheviking Finally wrote this. I ended up doing exactly the concept I set up above, and I added some unit tests to validate that the idea works. 

Meta values can be passed. It's just not documented anywhere and can be a bit of a pain to figure out. But here is some example code to show how a donation can be added: 
```
$campaign_id = 291; // ID of Campaign 4

$args = array(            
    'status' => 'charitable-completed', 
    'gateway' => 'manual', 
    'note' => '',
    'campaigns' => array(
        array( 
            'campaign_id' => $campaign_id,
            'amount' => 50,
            'campaign_name' => 'Campaign 4'
        )
    ), 
    'user' => array(
        'first_name' => 'Matthew',
        'last_name' => 'Murdoch',
        'email' => 'Matthew.Murdoch@example.com'
    )
);

$donation_id = charitable_create_donation( $args );
```

Internally, `Charitable_Donation_Processor` uses the `get_donation_data_value()` method to retrieve specific values from the passed values (`$args` in our example above). `Charitable_Donation_Processor::save_donation_meta()` is responsible for adding meta after the donation is created and it includes the `charitable_donation_meta` filter, so you can use that to add custom meta fields to be stored with the donation.
