### ISSUE TITLE
Use default edit.php?post_type=donation

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#110]
Instead of the custom `admin.php?page=charitable-donations-table` page, I think you can use the core `edit.php?post_type=donation` page with a few tweaks. with a little bit of style it's not far off and if I really tried I might be able to get the exact same look as currently in Charitable without needing custom `admin.php` pages. 

![image](https://cloud.githubusercontent.com/assets/507025/13323894/80585e20-dba9-11e5-8436-c1c443ed8dc7.png)

**Comment by TerenceMilbourn** [comment]
Yay, go Kathy!!!

**Comment by ericnicolaas** [comment]
@helgatheviking I have spent the afternoon looking at this. I performed a `rebase` against `master`, which was a bit tricky, but I don't believe I have lost anything other than the inclusion of the `$donation->get_donation_total_html()` method, which I don't feel is necessary while we have `charitable_format_money( $amount )`.

I have pushed my changes up to https://github.com/Charitable/Charitable/tree/issue/110. 

I made a few small CSS changes, including the removal of the border/background. I'm not 100% convinced about that, but going to try it out for now.

I found why the bulk actions had been removed and got that back in there, but it's missing any of the custom bulk actions. The link to the Trac ticket you gave is broken; could you post the link?

I'm still quite unconvinced about the layout of the filters + actions at the top. Bulk Actions feels awkward alongside the date filters, and the pagination. I don't mind having the Search field up above on the right, but everything in that bar below feels quite cluttered. And looking at the way WordPress builds this page, it doesn't look like we have much flexibility over where to place Bulk Actions in relation to the rest of the filters. 

At this point, I'm not feeling that the benefits of switching to `edit.php?post_type=donation` outweigh the downsides listed above. I know it's nice to use standard WP, but this just feels like it's too restrictive.  

Beyond the fact that it's not standard WP, what are the other main downsides you see to keeping the status quo of a custom admin page? How does this impact your work with Recurring Donations?

**Comment by helgatheviking** [comment]
Hi Eric, I think maybe this is the [trac ticket](https://core.trac.wordpress.org/ticket/16031). Apparently you can't *add* bulk actions via the filter, so I was thinking I'd have to try to hand-code them, probably similar to how you've added them on your custom pages. 

>Beyond the fact that it's not standard WP, what are the other main downsides you see to keeping the status quo of a custom admin page? How does this impact your work with Recurring Donations?

Well the main reason is that the admin looks like other admins, but the benefit to Recurring is that it's very easy to set up the recurring page. It's not that hard to duplicate your custom pages, but it's even easier this way.

I need to dust off your branch and play around a little more, but you're right that it is difficult to move pieces around in the default admin.

**Comment by helgatheviking** [comment]
Well at full-width, I think it looks pretty good to me:
![image](https://cloud.githubusercontent.com/assets/507025/16673575/69fe6a10-447d-11e6-81b5-be37d32c3905.png)

If the dates were numerals 24/04/2016 (or american style 04/24/2016) then you could shrink the inputs a little. And I'd probably switch the export button back next to the "filter" button. 

At medium width it doesn't look great:

![image](https://cloud.githubusercontent.com/assets/507025/16673690/5fc21334-447e-11e6-8633-d27e3d9e9dfc.png)

but it behaves the same as other post types

![image](https://cloud.githubusercontent.com/assets/507025/16673701/8a14c2da-447e-11e6-9938-c15d1ecf2a2f.png)

**Comment by ericnicolaas** [comment]
Yeah, a good portion of my disillusionment is coming from the fact that I'm doing most of my development on a laptop sans monitor, which means I'm seeing the second screenshot by default.

**Comment by ericnicolaas** [comment]
I'm leaving this for the 1.4 release. But after chatting about this with @helgatheviking, one option that I think would be worth considering is to adopt something like the Stripe payments filtering page:

<img width="958" alt="screenshot_2016-07-08_11_05_47" src="https://cloud.githubusercontent.com/assets/676582/16685692/ee59489c-454b-11e6-89cd-cb7ce28a3af4.png">

When you click on the Filter button in Stripe, it pops up with a little dropdown: 

<img width="292" alt="screenshot 2016-07-08 11 06 40" src="https://cloud.githubusercontent.com/assets/676582/16685698/fbacd95a-454b-11e6-81d6-64da789d77b7.png">

Quite simple, but actually provides a lot of opportunity for adding _more_ filters over time. I'm not convinced we need to use a dropdown like Stripe; we could use a modal popup like we currently do for the Export button. 

If we went down this track, the UI could be a little like this (ignore the ugly buttons, courtesy of Skitch):

<img width="1093" alt="stripe-ish_donations_table" src="https://cloud.githubusercontent.com/assets/676582/16685640/954aa3e0-454b-11e6-9c73-2dcfa0a8db02.png">

**Comment by helgatheviking** [comment]
So something more like this: ![image](https://cloud.githubusercontent.com/assets/507025/16701547/66760eb4-452e-11e6-983b-29d8781a2efc.png)

**Comment by helgatheviking** [comment]
Check out my [branch 11](https://github.com/helgatheviking/charitable/tree/issue/110) for a modal filter. One thing that I'm aware of is that if you filter by ID and there are no matching donations, it shows all the donations.

**Comment by helgatheviking** [comment]
Here's a [screencast of the dropdown](http://d.pr/v/12XpZ) stripe-style look.
and here's a [screencast of the modal](http://d.pr/v/1dcuS) that mimics the export modal. The datepicker wasn't working yet at the time of the screencast, but it is working in my [`issue/110`](https://github.com/helgatheviking/charitable/tree/issue/110) branch

**Comment by ericnicolaas** [comment]
@helgatheviking Finally had a chance to look at this. I'm quite happy with it. I pulled from your branch, made some changes and pushed everything up to https://github.com/Charitable/Charitable/tree/issue/110b.

Two minor issues remain: 

1. The "Pending" status tag should be grey I think (@wesfranklin was that your thought?)
2. A "Clear" button would be nice, and there's plenty of space for it now

**Comment by helgatheviking** [comment]
I think the stylesheet isn't quite right at 110b. Here's what I see when I checkout that branch. 

![image](https://cloud.githubusercontent.com/assets/507025/17010450/a84ecab6-4ec9-11e6-8ec2-5df8089c4717.png)

a 3rd issue for me is default compatibility with `restrict_manage_posts`. I want to give a thought to how to handle that, but I'm in handball camp and trying to juggle a client project.

**Comment by helgatheviking** [comment]
The modal script action isn't happening either. Are you sure the 110b branch is up to date?

**Comment by ericnicolaas** [comment]
Sorry, might be needing a `grunt build`. I'll check and push changes.

**Comment by ericnicolaas** [comment]
@helgatheviking Try it now.
