### ISSUE TITLE
Payment gateways return by default back to campaign page

### ISSUE THREAD

**Issue by remcotolsma** [Charitable/Charitable#117]
We received a request to return to the campaign page if user cancels the payment. What is the best way to get campaign page permalink for a donation (ID)? We currently have the following code:

```
	/**
	 * Get the default return URL.
	 *
	 * @since 1.0.3
	 * @param Charitable_Donation $donation
	 * @return string URL
	 */
	private static function get_return_url( $donation ) {
		$url = home_url();

		$campaign = reset( $donation->get_campaign_donations() );

		if ( false !== $campaign ) {
			$url = get_permalink( $campaign->campaign_id );
		}

		return $url;
	}
```

Maybe this can also be improved for the PayPal gateway:
https://github.com/Charitable/Charitable/blob/1.3.3/includes/gateways/class-charitable-gateway-paypal.php#L151

Maybe it's also nice to have an cancel/failed payment page, so we can get a cancel URL like this:

```php
$url = charitable_get_permalink( 'donation_cancel_page', array( 'donation_id' => $donation_id ) );
```

**Comment by ericnicolaas** [comment]
@remcotolsma I think my preference for this is to return the donor to the campaign by default, but display some sort of notification to acknowledge the cancellation and hopefully prompt them to try again & complete it. However, it also makes sense to have the option of creating a static page that donors are redirected to, which can be configured via _Charitable_ > _Settings_. 

Going to assign this to the 1.4.0 milestone for now.
