### ISSUE TITLE
Allow donations to be edited

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#118]
> We have donors who accidentally misspelled their names, or didn't capitalize them. I'd love to be able to fix these without making them re-donate.

**Comment by helgatheviking** [comment]
:+1:  for some metaboxes in the admin

**Comment by ericnicolaas** [comment]
Pinging @wesfranklin to get his thoughts. 

One consideration is that I would also like to add the ability to create donations via the admin. This has been requested regularly enough and I feel it should be part of the core plugin.

Given that, there are three possible views of a single donation in the admin: 

- Create a new donation
- Edit an existing donation
- View an existing donation

So the question is, do we want a single UI for all three of the above, separate UIs for each, or some kind of combination?

**Comment by helgatheviking** [comment]
I think it would be the same UI. A regular post with metaboxes always has the same UI. Here's an example of the "shop" order in various states...

"new"
![image](https://cloud.githubusercontent.com/assets/507025/17282688/160b8736-576e-11e6-9320-2174497d2f7b.png)

"edit" (looks like the same whether editing a new/existing order... except existing would have pre-filled data)
![image](https://cloud.githubusercontent.com/assets/507025/17282705/4a6642aa-576e-11e6-9d0e-c645722efbcc.png)

"view"
![image](https://cloud.githubusercontent.com/assets/507025/17282670/da776276-576d-11e6-993a-6d0f23ba4a95.png)

**Comment by wesfranklin** [comment]
Yeah I think this makes sense. Basically the same UI for all 3 - the New Donation has the empty fields, Edit has the same fields but they're filled in, and View has a collapsed version of the filled in fields.

**Comment by ericnicolaas** [comment]
Alright, so I've started work on refactoring the donations page layout to split the campaign donations from the initial donation overview. See https://github.com/Charitable/Charitable/tree/issue/118

**Comment by ericnicolaas** [comment]
This is the current state of things: 

<img width="1082" alt="screenshot 2016-08-12 12 28 46" src="https://cloud.githubusercontent.com/assets/676582/17611653/5b1faa78-6088-11e6-8f42-d94939f98b55.png">

The concept under consideration is that an Actions metabox will be added to the top right, where you can select an option to edit the campaign. This then opens up a new view of the page, where the "Donation Details" box becomes editable and the Campaign Donations table becomes editable.

**Comment by helgatheviking** [comment]
I think if you add a little edit icon to the details metabox, it would serve as a nice trigger for switching the "view" to the text inputs needed for editing. 
![image](https://cloud.githubusercontent.com/assets/507025/18598999/a605ea6c-7c1b-11e6-98b2-dfbd84370a59.png)

**Comment by maharzan** [comment]
This would be very handy. +1

**Comment by ericnicolaas** [comment]
With the form working pretty solidly now (see #241 for screenshots), I'm working on how to link to the edit form for a campaign. This is what I have so far:

### Donation View

<img width="1095" alt="screenshot 2017-09-26 10 07 13" src="https://user-images.githubusercontent.com/676582/30837227-8f5c12c4-a2a2-11e7-83e1-a7bd1d8a5de1.png">

### Donations Table

<img width="1066" alt="screenshot 2017-09-26 10 08 11" src="https://user-images.githubusercontent.com/676582/30837265-c5f7df7a-a2a2-11e7-8eca-85d034129e88.png">

@wesfranklin Would love your thoughts.

**Comment by ericnicolaas** [comment]
Actually, one issue with the way this is shown on the details page is that the donation actions box it's inside of is only shown if there are actions; so it's possible the box wouldn't show at all, providing no way to link to the edit form.

**Comment by helgatheviking** [comment]
Where's the original "save" button? Save and edit should always been in that metabox.... if no actions, you simply hide the drop down. my 2 cents anyway.

**Comment by ericnicolaas** [comment]
I have considered that idea, that there would be an option in that dropdown list to edit the campaign, so when you click the button then it goes to the edit form. My concern there is primarily with having the option feel a little buried, and also that the "Edit" action is quite different in nature to all the other actions there (i.e. when you click the button, it's just a glorified link click, not really an "action" per sé). 

But I would love to have more points of view on this. I'll mock up the idea of having it in the Donation Actions meta box, as well as a few more ideas I'm playing with.

**Comment by ericnicolaas** [comment]
### Variation 1

<img width="1109" alt="screenshot 2017-09-26 10 29 21" src="https://user-images.githubusercontent.com/676582/30837792-b55d3698-a2a6-11e7-82b5-66f1728fd78b.png">

### Variation 2 (with colour)

<img width="1095" alt="screenshot 2017-09-26 10 36 42" src="https://user-images.githubusercontent.com/676582/30837795-bca33a2e-a2a6-11e7-9262-fb468ba03b95.png">

### Variation 3 (Donation Actions)

<img width="396" alt="screenshot 2017-09-26 10 41 16" src="https://user-images.githubusercontent.com/676582/30837872-41d04e1c-a2a7-11e7-8741-6772bd06f5a5.png">

<img width="1092" alt="screenshot 2017-09-26 10 41 05" src="https://user-images.githubusercontent.com/676582/30837873-43eafda0-a2a7-11e7-9281-91dd74467e6b.png">

**Comment by ericnicolaas** [comment]
Pinging @wesfranklin, @helgatheviking, @rafecolton, @lukepg, @SooBahkDo and @maharzan — to all of you, how do you feel about the UI changes shown above? I know it can be hard to imagine how it would work just from a screenshot, but would love your feedback and any questions. 

Also, see #241 for a screenshots of what the edit form actually looks like (it doesn't look like the above at all).

**Comment by helgatheviking** [comment]
I'm also still a fan of having the edit donation form inside the existing metabox, but I understand why you want to keep it separate. 

What about a 4th variation that has the edit link and "save" button in the actions metabox?

**Comment by ericnicolaas** [comment]
@helgatheviking Do you mean the edit link that I had in my earlier comment? 

What would the Save button do?

**Comment by helgatheviking** [comment]
Errr... well I guess I am still imagining the edit happening in the same place (which mimics the rest of WP posts more closely).  If it is separate, you're right, you don't need a save button there.

**Comment by rafecolton** [comment]
I like the button at the top (above `Status: Pending`), as it feels more intentional. Editing a donation is a more significant action than resending an email. 

If you could edit the fields without leaving the page, then the UX could go like:

1. Click edit button to begin editing
1. Button text changes to `Save Changes` and bar goes from gray to orange to indicate significant action occurring
1. Donation fields become editable in place or entire page section replaced with edit screen from #241 
1. Upon saving, bar color, button text, and info is restored to original state (with new data)

I'm imagining it would be easier to implement in a separate page than what I've described above. If so, I prefer the link in the metabox to a button in the metabox. I expect the blue button in the upper right to submit or save something—that is, complete an action not initiate one. The button can be reserved for submitting the request from the action selected from the dropdown, and it can be hidden until an action is selected.

**Comment by ericnicolaas** [comment]
@helgatheviking & @rafecolton: Thanks for the feedback. You've both mentioned your preference for having the edit happening in the same place. What are the main benefits to having the edit in the same place? What are the drawbacks to having an edit form in a separate page, in a form that doesn't look the same as the donation details page?

**Comment by wesfranklin** [comment]
@ericnicolaas I think having the edit form in a separate page is fine. I also think it seems odd to use a button for the Edit - a link seems more appropriate like you had originally.

**Comment by helgatheviking** [comment]
It's not bad to have it in a separate page, but most other post types edits in place so it will feel more like traditional WP that way. That's my main thinking behind it anyway.

**Comment by rafecolton** [comment]
> It's not bad to have it in a separate page

Agree with this. 

Having it in the same page seems a little cleaner—less jumping around. My recommendation is based purely on UX and ignores differences in implementation difficulty.

**Comment by ericnicolaas** [comment]
Thank you @memerson75, @helgatheviking, @wesfranklin and @rafecolton for the feedback. I have now merged all my changes, and gone with something closes to variation 1:

![screenshot 2017-09-29 16 42 19](https://user-images.githubusercontent.com/676582/31004835-3cdbdada-a535-11e7-8a22-cdb154b13c96.png)

I am still more than open to changing this.

You can test all the changes out with the latest `master` — any testing and feedback would be really, really helpful. Here's what's changed:

1. Adding and editing donations is done
2. Added Donation Fields API (see #402) 
3. Added Form View API (see #401)

2 & 3 are both under the hood — you should not _see_ any differences. But they are very significant changes and affect how all the forms in Charitable are built (donation, campaign, registration, password reset, etc.).
