### ISSUE TITLE
Emails are not being sent when campaigns are created and donations are made

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#125]
There are 7 different emails:
Donor: Donation Receipt
Admin: New Donation Notification
Admin: Campaign Ended Notification
Admin: New Campaign Notification
Campaign Creator: New Campaign
Campaign Creator: Campaign Ending
Campaign Creator: Donation Notification

None of these is being triggered.

**Comment by ericnicolaas** [comment]
@QloudPress Have you activated these emails via Charitable > Settings > Emails?

**Comment by QloudPress** [comment]
Absolutely, And the previews are blank apart from the Title.

**Comment by ericnicolaas** [comment]
Are you getting any other emails from your site, like password reset emails?

**Comment by TerenceMilbourn** [comment]
No problem ...
                                                                                                                                                                                                                                                               
Delivered-To: admin@wpfunder.org
Received: by 10.182.11.8 with SMTP id m8csp1438131obb;
        Wed, 20 Apr 2016 15:12:09 -0700 (PDT)
X-Received: by 10.50.168.100 with SMTP id zv4mr6537788igb.4.1461190329751;
        Wed, 20 Apr 2016 15:12:09 -0700 (PDT)
Return-Path: <support@wpfunder.org>
Received: from mail-ig0-x22c.google.com (mail-ig0-x22c.google.com. [2607:f8b0:4001:c05::22c])
        by mx.google.com with ESMTPS id 14si72054ios.31.2016.04.20.15.12.09
        for <admin@wpfunder.org>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 20 Apr 2016 15:12:09 -0700 (PDT)
Received-SPF: pass (google.com: domain of support@wpfunder.org designates 2607:f8b0:4001:c05::22c as permitted sender) client-ip=2607:f8b0:4001:c05::22c;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@wpfunder.org;
       spf=pass (google.com: domain of support@wpfunder.org designates 2607:f8b0:4001:c05::22c as permitted sender) smtp.mailfrom=support@wpfunder.org
Received: by mail-ig0-x22c.google.com with SMTP id m9so50217158ige.1
        for <admin@wpfunder.org>; Wed, 20 Apr 2016 15:12:09 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=wpfunder.org; s=google;
        h=from:sender:reply-to:mime-version:date:message-id:subject:to;
        bh=lx5eq5/XJhbX4NfCNQ0mmKBx9ACqh0TpXRX8B+HY0t8=;
        b=HwgbEYWGM77ZhC3/kxB0fqAzaWYKXLnn0211MrJ+/nMoqNJa3YJuafe/T+Oi5YFxu3
         VFR97dC8CsdkXiQzkLYz/ipNk8vvZnuwbAcUv8hj+kawfXrQBz7DB5xA8BGIuVTz6UNq
         imKT/1jv7lWKzKekQD0QKZ7ZoBkPrtipOq+cI=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:from:sender:reply-to:mime-version:date
         :message-id:subject:to;
        bh=lx5eq5/XJhbX4NfCNQ0mmKBx9ACqh0TpXRX8B+HY0t8=;
        b=EcYdjv4k/xW9637ttJOcrbv/sliq6mof1MQx6N1jBbrHiBueThpH4+0S04Nv57QDA2
         Ye9E/chVPID+kLvhDkejU9iziIuovz3Y2/BGDWIfD7NT+TTdRIu/bceIIldzs7NTSBwS
         WOJFERAeomLrTqw7UtSLgE7xH2Yb7BsFfCf0wSbvOdymgFb1qTUIP5OUBl9bABZCHxsW
         9hyp7pfC+EUVZbd6V1xcfgQ2kHhsKfITIfW7Hbu1y4nFg2NLaKNJwLIj/e7RjaQ40+/J
         aPPkqyE48xJRnqlucyGq6L+dSQM1lQdcCylAoXMwYC0BCrduLU31cre+ojzurPdu8MXD
         ZbIg==
X-Gm-Message-State: AOPr4FUgbKL9OtHVOZU0N1euOjk/pBQgnmTN6meIc4ZkLiHJ2uohUYbtPbynNSOlCJ7bCYpzHrqqbMkJ9ZknL7PbDsM=
X-Received: by 10.50.118.225 with SMTP id kp1mr6747515igb.9.1461190329113;
 Wed, 20 Apr 2016 15:12:09 -0700 (PDT)
Received: from 551099728774 named unknown by gmailapi.google.com with
 HTTPREST; Wed, 20 Apr 2016 18:12:08 -0400
X-Mailer: Postman SMTP 1.7.2 for WordPress (https://wordpress.org/plugins/postman-smtp/)
From: WPFunder <support@wpfunder.org>
Sender: support@wpfunder.org
Reply-To: "'Fred'" <ff@rockville.com>
MIME-Version: 1.0
Date: Wed, 20 Apr 2016 18:12:08 -0400
X-Google-Sender-Auth: 5XMb0U6gb9dgTiUN8MZbzaV6o4s
Message-ID: <CAHA7KLO=+MX0RwbJ7ODLZEajPGE_FSGyCVNCrT3H+R7_ZMxnxw@mail.gmail.com>
Subject: New Message From WP Funder - Howdy
To: admin@wpfunder.org
Content-Type: text/plain; charset=UTF-8

How do you like this test email Terence?
Website: This is a test

**Comment by TerenceMilbourn** [comment]
Looks like that worked Eric.  I now have an email announcement that a campaign was created. What needed to be changed?

**Comment by ericnicolaas** [comment]
I didn't change anything; just submitted the campaign. I also received a notification myself. 

With the donation notifications for the donor, admin and campaign creator, bear in mind that all of those are only sent when the donation is marked off as paid -- not when it is pending.

**Comment by TerenceMilbourn** [comment]
Ah, maybe that's it then. I need to be able to proceed further with Stripe then, in order to see those emails
