### ISSUE TITLE
Fundraising Goal & Length fields are not styled in Divi theme

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#126]
Fundraising Goal & Length fields in Divi theme are not styled because Divi does not provide any styling for some reason. Forwarded in Divi ticket #537072 for comment/resolution.

**Comment by TerenceMilbourn** [comment]
It took me 10 days to get an answer out of them for the last issue.

**Comment by TerenceMilbourn** [comment]
So far I got this from Andrei Nahaev ~ "I will add this issue into our bug tracker but I am afraid there is no exact date on when it will be included in the theme. Our Dev team will fix it as soon as it possible."

**Comment by ericnicolaas** [comment]
Closing this since it's not something we should solve on the Charitable side of things at this time.
