### ISSUE TITLE
Prevent custom donations being disabled without suggested donations

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#127]
If you do not enable custom donations and you don't provide suggested donations, you can still submit the donation form but it doesn't work as expected. Reports suggest that with PayPal this will actually go through and result in a $5 donation. 

I think this should be dealt with in two ways: 

- [x] Server side checking on `save_post`. Auto-enable custom donations if suggested donations are empty.
- [x] Custom donations is ticked by default and cannot be unticked (i.e. it's `disabled`) unless suggested donations have been provided.

**Comment by TerenceMilbourn** [comment]
+1 for "Custom donations is ticked by default and cannot be unticked (i.e. it's disabled) unless suggested donations have been provided." but I think you mean "i.e. its enabled", don't you?

**Comment by ericnicolaas** [comment]
@TerenceMilbourn No, I do mean disabled, as in the html element will have the `disabled` attribute set on it, which prevents it from being changed.
