### ISSUE TITLE
Add a Donors shortcode

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#129]
It has been requested to be able to see a list of donors within campaign content. The Donors widget obviously displays this already, but creating a donors shortcode to match makes sense.

**Comment by TerenceMilbourn** [comment]
Have you thought any more about building the whole campaign page from shortcodes in order to allow the page layout to be redesigned to suit to theme being used.

For example, using a theme like Divi, or maybe even Make, I would use the theme's page builder to add tabbed pages to the campaign page and then locate the comments in one tab, the list of donors in another, and maybe more elements in several more.

**Comment by ericnicolaas** [comment]
@TerenceMilbourn I'm on board with adding more shortcodes like this Donors shortcode. 

It sounds like what you are suggesting is to use shortcodes to define a page template that is used as the default template for all campaigns. Am I understanding correctly? The challenge with this is that all the builders I have used (Divi, Make, Beaver Builder & Layers) are not set up to do this. They are set up to create unique layouts for individual pages/posts. True, you can often save those layouts and then reuse them on other pages/posts, but that's still not the same as defining the _default_ template used for all campaigns created. With any of the page builders above, if you create a page/post and _don't_ use the builder on it, they still provide you with a default template as a fallback -- and there is no way to alter this default template using the builder. Does that make sense? 

I have toyed with the idea of adding Divi Builder support for campaigns but decided that this is ill-advised considering that: a) Divi doesn't provide a clean API for enabling the builder for custom post types; b) Divi itself doesn't do this for WooCommerce products, which it adds support for elsewhere in the Builder.

**Comment by TerenceMilbourn** [comment]
Yes, that's what I was thinking, but it actually doesn't have anything to do with the theme. It would still be theme agnostic. In other words, if you didn't like the default Charitable campaign template, you could roll your own using shortcodes, and then save it as your site's default template. In other words, you would  also include a custom campaign template containing the basics, specifically configurable for this purpose, So when you set up the site you can chose between either the standard campaign template, or the custom campaign template we have already configured. Would that make sense?

**Comment by ericnicolaas** [comment]
This is done, though I'd appreciate thoughts on the styling. The shortcode and the widget both rely as much as possible on the same code and CSS, so they are very similar. Arguments overlap quite a bit too. Here are the parameters for the `[charitable_donors]` shortcode: 

* **`number`** Number of donors to show. Default is `10`.
* **`orderby`** May be `date`, `donations` or `amount`. Default is `date`.
* **`order`** May be `ASC` (ascending order) or `DESC` (descending order). Default is `DESC`.
* **`campaign`** May be set to the ID of a campaign, `current` to display the donors to the campaign currently being viewed, or `all` or `0` to display donors to any campaign. Default is `0` (donors to any campaigns).
* **`distinct_donors`** Only show unique donors. May be set to `0` (don't show distinct) or `1` (show distinct). If a donor has donated more than once, they will only appear in the list once, with their donation amount calculated based on all their donations. Default is `1`.
* **`orientation`** May be `vertical` or `horizontal`. Default is `horizontal`.
* **`show_name`** Whether the name should be shown. May be `1` (show) or `0` (don't show). Default is `1`.
* **`show_location`** Whether the donor's location should be shown. May be `1` (show) or `0` (don't show). Default is `0`.
* **`show_amount`** Whether the donor's donated amount should be shown. May be `1` (show) or `0` (don't show). Default is `0`.
* **`show_avatar`** Whether the donor's avatar should be shown. May be `1` (show) or `0` (don't show). Default is `0`.
* **`hide_if_no_donors `** Whether the shortcode should display anything if no one has donated yet. May be `1` (hide) or `0` (don't hide). Default is `0`.

## Horizontal Layout (default)

<img width="614" alt="screenshot 2017-07-24 10 35 24" src="https://user-images.githubusercontent.com/676582/28504520-ed3a181a-705b-11e7-9faf-0717dbd22165.png">

## Vertical Layout

<img width="618" alt="screenshot 2017-07-24 10 36 42" src="https://user-images.githubusercontent.com/676582/28504536-28dc253e-705c-11e7-94c0-63a5e4b4df49.png">

## Vertical Layout in the widget

<img width="248" alt="screenshot 2017-07-24 10 40 49" src="https://user-images.githubusercontent.com/676582/28504561-ac313654-705c-11e7-968c-c7615ea93c79.png">

**Comment by wesfranklin** [comment]
@ericnicolaas The text in the widget is obviously smaller, I assume the shortcode just uses the body paragraph size? And way to make it smaller?

**Comment by wesfranklin** [comment]
Otherwise looks good.

**Comment by ericnicolaas** [comment]
@wesfranklin Which of the following do you think looks better?

## Option 1

![screenshot 2017-10-12 16 44 00](https://user-images.githubusercontent.com/676582/31483691-945487da-af6c-11e7-86b9-20f22e9e1352.png)

## Option 2

![screenshot 2017-10-12 16 43 52](https://user-images.githubusercontent.com/676582/31483689-932113b0-af6c-11e7-8338-0b472d30e327.png)

With the second option, I have set an explicit width of 100px, which matches up with the default thumbnail size. It means that longer names with large text end up splitting over multiple lines, but it does keep everything much neater.

**Comment by ericnicolaas** [comment]
We could also add a "width" parameter to the shortcode to allow people to choose a wider block per donor.

**Comment by wesfranklin** [comment]
Yeah, adding a width parameter could be good. I'm not sure how picky people will be with this, but its a nice addition.

**Comment by ericnicolaas** [comment]
@wesfranklin Yep. So you're happy with option 2 above?

**Comment by wesfranklin** [comment]
Yep

**Comment by ericnicolaas** [comment]
Docs added to https://www.wpcharitable.com/documentation/donors-shortcode/
