### ISSUE TITLE
Type of Campaign | Funds Recipient

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#130]
I am not able to set the Funds Recipient. 

Version info: http://screencast.com/t/YVEAcURoUw7

I still don't have access to the input field.

![2016-05-11_1116](https://cloud.githubusercontent.com/assets/4005326/15177785/e2708eba-1769-11e6-936d-f5aef5e47f9b.png)

**Comment by TerenceMilbourn** [comment]
Have you been able to make any advance with this issue Eric?

**Comment by ericnicolaas** [comment]
I'm working on an update for Ambassadors that will resolve this.

**Comment by TerenceMilbourn** [comment]
ETA?

**Comment by ericnicolaas** [comment]
This week

**Comment by TerenceMilbourn** [comment]
Whoohooo!  :-)

On 24 May 2016 at 02:13, Eric Daams <notifications@github.com> wrote:

> This week
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Charitable/Charitable/issues/130#issuecomment-221140550>
>



-- 
PGP Key ID: E255694AC09CB76F
http://keyserver.pgp.com

**Comment by ericnicolaas** [comment]
@TerenceMilbourn Just a heads up that Ambassadors 1.1.1 was just released, resolving this problem for any new projects. Unfortunately, due to this bug, campaigns previously submitted might still display a blank for the Funds Recipient since they did not correctly store the type of recipient.

**Comment by TerenceMilbourn** [comment]
Not convinced yet that 1.1.1 fixes it Eric. 

Still testing, but the initial results are not positive.

**Comment by TerenceMilbourn** [comment]
The control panel speed has dropped to include 12 to 16 second waits again.

I am going to leave 1.3.7 deactivated for a longer period of time now and see if the slowness returns.

![2016-05-25_1208](https://cloud.githubusercontent.com/assets/4005326/15538043/974f361c-2271-11e6-88f8-ec91f4ddc9f2.png)

**Comment by TerenceMilbourn** [comment]
Eric, I have had the Charitable plugin deactivated for the last 3 hours while I was working on the site. This included adding new and activating already installed plugins. 

There has not been any sign of a slowdown in the back end while Charitable was deactivated. 

Then I reactivated 1.3.7 and everything was normal for a while, but as soon as I reactivated another plugin the 12-16 second delay returned.

So, I can definitely say this issue is not resolved yet.

**Comment by TerenceMilbourn** [comment]
Still checking whether the 1.1.1 release works as you expected.

**Comment by TerenceMilbourn** [comment]
Nope, still exactly the same. No type of campaign of funds recipient data is accessible.

**Comment by TerenceMilbourn** [comment]
This issue is marked [CLOSED] for some reason not obvious to me.

**Comment by TerenceMilbourn** [comment]
How is this "type of campaign/funds recipient" section supposed to work and look?

I don't know because I have never seen it.

**Comment by ericnicolaas** [comment]
@TerenceMilbourn If you create a new campaign via the frontend form do you see any data in the Funds Recipient tab for it? The update will not have changed anything for previous campaigns.

**Comment by TerenceMilbourn** [comment]
Yes I get the bit about it not changing the existing structure, but I only created new campainges from the back end. I'll set up a test user and try it from the front end.

**Comment by TerenceMilbourn** [comment]
Not going too well Eric.

When I saved the new campaign WordPress created one copy and Stripe made another ~ http://screencast.com/t/7YVLb52lQF

But nowhere is there any sign of a Funds Recipient tab at all,

Can you please take a look for me please, I am anxious to get this thing launched.

**Comment by TerenceMilbourn** [comment]
Do you know what this is? 

http://screencast.com/t/NCvmNuMcC1rg

That miniaturized version of the whole front page has appeared again at the bottom of the campaign post

**Comment by ericnicolaas** [comment]
> That miniaturized version of the whole front page has appeared again at the bottom of the campaign post

No idea what this is, and I don't see how Charitable would be causing it. Could you try deactivating all other plugins and see if the issue persists? If it goes away, then reactivate plugins one at a time until it reappears. 

> When I saved the new campaign WordPress created one copy and Stripe made another
> But nowhere is there any sign of a Funds Recipient tab at all

I sent you an email. Let's follow up there.

Cheers, 
Eric
