### ISSUE TITLE
wpadminbar in the footer of each campaign

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#131]
Eric, this is a test campaign you set up on my site. 

Notice what looks like a widget at the bottom?

![2016-05-11_1131](https://cloud.githubusercontent.com/assets/4005326/15178239/686f4a0e-176c-11e6-89f9-d190faade44b.png)

I took a look at the back-end and this is what I see ...

![2016-05-11_1130](https://cloud.githubusercontent.com/assets/4005326/15178285/9bc76bac-176c-11e6-85b1-6a9082e74674.png)

**Comment by ericnicolaas** [comment]
Well that is _exceedingly_ strange! I tried to see this in action; logged into wpfunder and accessed a campaign, but I'm not seeing the issue there. Is this still happening for you? If so, could you send me a link?

**Comment by TerenceMilbourn** [comment]
Its not there now. 

My best guess was that it was something to do with Postmatic/Epoch, both of which have since been updated.

We shall never know now... 8^(

**Comment by ericnicolaas** [comment]
As long as it's not Charitable's fault, I'm happy :)

**Comment by TerenceMilbourn** [comment]
Well, it can't be proven either way.

But the thing we can say is ~ at least for the moment ~ its gone now!



On 23 May 2016 at 12:12, Eric Daams <notifications@github.com> wrote:

> As long as it's not Charitable's fault, I'm happy :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Charitable/Charitable/issues/131#issuecomment-220952041>
>



-- 
PGP Key ID: E255694AC09CB76F
http://keyserver.pgp.com
