### ISSUE TITLE
With Charitable active it slows down the control panel

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#133]
I click on "Installed Plugins" in the control panel and [... 12 seconds later] it loads the page. 

I then click the "Active" tab and [... 12 seconds later] it lists 27 plugins. 

I want to see if I have installed "micro-themer" CSS plugin already, so I type "micro" into the search window and [... 12 seconds later] it gives me the message -- "No plugins found for “micro”.  

So then I click on [add new] [upload plugin] and [... 25 seconds later] the plugin installs. 

I then activate the plugin and [...30 seconds later] the plugin activates.

To find the culprit I deactivated all plugins except "Charitable" and found it made no difference - everything was still just as slow. 

I then deactivated "Charitable" and [... 13 seconds later], it deactivated.

I then reactivated the "Charitable" plugin [... 0 seconds later] it reactivated.

Now when I click on "Installed Plugins" or the "Active" tab, it lists them both [... 0 seconds later]. 

Also, the other plugins also now list [... 0 seconds later].

If I activate a plugin that has already been installed, Charitable doesn't seem to have a problem with that. But if I install a new plugin with Charitable loaded and activated, it goes back to slowing down the control panel again [12-30 seconds later] it activates. 

If I then deactivate and reactivate Charitable again [12-30 seconds later] everything goes back to normal and everything appears [0 seconds later].

Eric, I have tied this with many plugin combinations and this can be replicated here. On this site Charitable is doing something globally which is slowing down the plugin access and activation to the point of making the control panel virtually unusable when it is active.

**Comment by TerenceMilbourn** [comment]
I think I should add, if I leave it for a while, with Charitable enabled, then the slow control panel behaviour returns. And if I deactivate and reactivate Charitable the control panel behaviour goes back to normal again.

**Comment by TerenceMilbourn** [comment]
Back end slowed to a crawl again after reactivating the new versions of Postmatic/Epoch, but after deactivating and reactivating Charitable again its flying.

**Comment by ericnicolaas** [comment]
My suspicion is that this is related to how Charitable calls back to wpcharitable.com to check for plugin updates. I have been able to replicate this on a test site, so will continue to investigate.

**Comment by TerenceMilbourn** [comment]
Yes, that would make sense. I also think their are other plugins having the same difficulty ~ maybe using the same scripts/utilities ~ I have also noticed this slow down recently on other sites too; sites don't have Charitable on them. But its very time-consuming to track them down.

**Comment by TerenceMilbourn** [comment]
After deactivate/reactivate, the Initial results for the update are looking good so far. The problem is the slowness can return at any time. The workaround of deactivate/reactivate works every time but finding out what triggers it is easier said than done.

**Comment by TerenceMilbourn** [comment]
Eric, I have had the Charitable plugin deactivated for the last 3 hours while I was working on the site. This included adding new and activating already installed plugins.

There has not been any sign of a slowdown in the back end while Charitable was deactivated.

Then I reactivated 1.3.7 and everything was normal for a while, but as soon as I reactivated another plugin the 12-16 second delay returned.

So, I can definitely say this issue is not resolved yet.

**Comment by TerenceMilbourn** [comment]
The short-term workaround is to remove the registration keys from all the plugins.

**Comment by ericnicolaas** [comment]
@TerenceMilbourn Just a heads up: In Charitable 1.4, this situation should be significantly improved. It took quite a bit reworking, but the whole process of checking for updated extension versions is now far more efficient. Thanks for reporting it!

**Comment by helgatheviking** [comment]
Resurrecting this because I'm seeing 20-60 second page loads for the charitable admin settings, locally and at my c9 demo.
