### ISSUE TITLE
"Update your details" halts donation payment process

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#135]
If you click on "Update your details" while processing a donation, the form pushes the DONATE button down below the bottom of the screen, so you cannot complete the donation. 

Clicking "Update your details" again should recover the screen but it doesn't, and scrolling only scrolls the background, so the donation has to be abandoned.

![2016-05-23_1251](https://cloud.githubusercontent.com/assets/4005326/15470104/42c04e56-20e6-11e6-9f6e-33074872a3e4.png)

**Comment by ericnicolaas** [comment]
Ouch, that's not good. Working on a fix for 1.3.7.

**Comment by TerenceMilbourn** [comment]
Confirm fixed.
