### ISSUE TITLE
Add a [charitable_donation_form] shortcode

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#136]
This would allow people to add a donation form to a separate page. 

Beyond the shortcode, there are a few other considerations to this: 
- When you view a campaign and click Donate, where should the button take you? It might be desirable for people to be able to have the Donate button go to a completely separate page instead of the /donate/ endpoint.
- Does the form have to be for a specific campaign, or can it be used to donate to multiple campaigns? If the latter, can you donate to multiple campaigns at once, or just a single campaign at once?

**Comment by ericnicolaas** [comment]
Added a basic snippet for this for now: https://github.com/Charitable/library/blob/master/donation-form/add-donation-form-shortcode.php

**Comment by ericnicolaas** [comment]
I think it would be _very_ nice to be able to add a [donation_form] shortcode that can then allow people to donate to any campaign, though perhaps to keep it simple, just one campaign at a time.

This way, you could have a standard `/donate/` endpoint on your site where all donations are made. If people land on that page by clicking on a Donate button for a specific campaign, the campaign is pre-filled; if they have landed on that page without that, then the first thing they do is select the campaign they would like to donate to.

There are several advantages to doing this:

1. For many people, this kind of basic donation form functionality is exactly what they're looking for. There would still need to be _a_ campaign, but the campaign doesn't have to be front and centre; the focus can be on the donation form.

2. Another common thing that people want is the ability for donors to select their designated fund when they donate. This is essentially providing that, by allowing donors to select a campaign. In that context, just think of a campaign as a designated fund, and you're done.

One consequence of this approach is that any per-campaign specific aspects of the donation form would need to be loaded via AJAX. In particular, the suggested donations / custom donation checkbox would need to be loaded for the particular campaign that the donor has chosen.

**Comment by helgatheviking** [comment]
This shortcode will be great for the beaver builder modules I am trying to build, though i think it should support a few more options than simply the `campaign_id`, such as overriding the default display mode.

**Comment by ericnicolaas** [comment]
@helgatheviking Thanks for the PR. It looks like a good step in the right direction.

I'm not sure about the idea of being able to choose the display mode. Right now, we have three display modes: same page, separate page and modal. If I add a `[charitable_donation_form]` shortcode to a page, I would assume it would show the form on the page. 

"Separate page" doesn't really make sense in this context. 

_Maybe_ modal could work, but then what do you show on the page? Just a button? In that case, would it make more sense to have a separate `[charitable_donate_button]` shortcode, which can open a modal or link to a particular campaign's form?

**Comment by ericnicolaas** [comment]
Someone today requested the ability to add a donate button that opens into a modal, which touches on what we discussed here. I have opened #403 with a potential approach to solving this, but I'm open to integrating this straight into `[charitable_donation_form]` instead.
