### ISSUE TITLE
Remove Google maps mouse-roll scroll effect

### ISSUE THREAD

**Issue by TerenceMilbourn** [Charitable/Charitable#138]
I use a full-width map of to show where each project/campaign is located globally.

Is it possible to edit the script to remove the mouse-roll scroll effect, so that a user can scroll down the page without first accidentally reducing the map to a minimum size?

![projects wp funder](https://cloud.githubusercontent.com/assets/4005326/15730849/2ba4b0d4-2868-11e6-9cb5-08fad1f67081.jpeg)

**Comment by ericnicolaas** [comment]
@TerenceMilbourn Yep, it looks like that's possible. I'm not going to change this in Charitable core, but you can override the template used for the maps by copying `charitable-geolocation/templates/shortcodes/campaigns-map.php` to `your-theme/charitable/charitable-geolocation/shortcodes/campaigns-map.php`. You can switch off the scrollwheel by setting `scrollwheel` to `false` when initializing the map (see lines 69-71 in the template above).
