### ISSUE TITLE
Several Issues with Donations

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#151]
Hi Eric,

I'm testing the donation workflow and have encountered several errors:

0. If the url parameter `?donation_id=` is present, it will allow the user to override another user's donation.  If this is used to redirect user back to the donation page with an error, perhaps it should be stored in the session?
0. If either the credit card number or cvv field is blank, the page 500's and the log shows the following error:

  > [07-Jul-2016 18:12:44 UTC] PHP Fatal error:  Call to a member function update_donation_log() on boolean in /Users/rafe/workspace/Charitable/build/charitable/includes/donations/class-charitable-donation-processor.php on line 533

0. When using a modal, if there is a credit card error, it redirects back to the campaign page with `?donation_id=` url param.  User has to re-open the donation modal to see the error.  Not sure what the correct behavior is here, but current behavior seems like it would be confusing for the user.
0. If `?donation_id=` is present on the campaign page when using a modal, then as described above, it allows the user to override another user's donation

**Comment by rafecolton** [comment]
Fixed item 2 with https://github.com/Charitable/Charitable/pull/152

**Comment by rafecolton** [comment]
Looks like item 3 was caused by a template I had that was overriding the donation form button. Only remaining issue is the `?donation_id=` url param.

**Comment by ericnicolaas** [comment]
Ouch, good catch.

**Comment by ericnicolaas** [comment]
We already store the donation key in the user's session, so they can see their receipt without logging in. I think that's the most secure way of testing for this: 

- Grab the donation ID from the query
- Find the donation key for that donation
- If there isn't a donation key or the donation key is not in the user's session, redirect the user to the donation page without the query string

**Comment by rafecolton** [comment]
Awesome job, thanks for the quick fix!
