### ISSUE TITLE
You must be logged in to view receipt

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#163]
When a user, who is not logged in, submits a donation, user is redirected to registration page with the error message "You must be logged in to view this receipt".  After creating an account, the user does not have access to the receipt.  This seems to be happening only with real payment gateways and not in test mode.

One possible solution is to allow users to see receipts with email address that match their account email address

**Comment by ericnicolaas** [comment]
@rafecolton Do you have Ninja Forms installed? If so, try deactivating it and see if the error persists. 

What _should_ happen is that the purchase key for the donation is stored in the user's session when they make the donation. This then allows them to read the receipt without being logged in.

**Comment by rafecolton** [comment]
This was a really weird one.  Turned out WP Engine was caching the `charitable_session` cookie.  They only have caching in production, which explains why it appeared to only be happening with real payment gateways. They set an exception so that they don't cache the cookie, and everything is now working as expected 😄

**Comment by ericnicolaas** [comment]
Do you know how WP Engine fixed this? Just wondering if there is something I can add to Charitable to prevent this happening for others.

**Comment by rafecolton** [comment]
They put in an exception in there system that says, "Don't cache cookies names `charitable_session`". They also put an exception for the donation and donation receipt pages, though I suspect those are not necessary. 

I don't know the specific mechanism for these exceptions, as I handled it with their support team over the phone.
