### ISSUE TITLE
Feature Request: Assign Donation to User Account

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#172]
If somebody creates an account after submitting a donation, it would be helpful to be able to assign that user account as the owner of the donation so the user can view the receipt page.  

It would also be helpful to have a link to the receipt page on the donation details page in wp admin.

Relates to https://github.com/Charitable/Charitable/issues/165

**Comment by helgatheviking** [comment]
As a followup, you'd also be able to have a "my account" area where users can view receipts for their donations.

**Comment by ericnicolaas** [comment]
I still think this is a good idea, but punting it to 1.6.0. I want 1.5.0 out and providing a good experience for doing basic editing of a donation (see #118), and then build on that in 1.6.0 with a better experience around how donors are defined (this is all a bit messy at the moment).

**Comment by ericnicolaas** [comment]
Heh, this is closed with 1.5.0.
