### ISSUE TITLE
Duplicate transactions, transactions declined by Authorize.Net get marked as pending

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#173]
When a user submits a donation with a fake credit card number (`4242424242424242` for example), the error message says "This transaction has been declined.", but the donation shows up in wp-admin as pending.  If the user hits the back button and tries again, the error messages says `A duplicate transaction has been submitted.`, but again, it gets logged in wp-admin as pending.

Is this the intended behavior in these two scenarios?

**Comment by ericnicolaas** [comment]
I've been able to reproduce this. Definitely not intended behaviour. Ideally the donation should be pending, but if the donor then tries again with the correct card number, it should update the existing donation.

**Comment by rafecolton** [comment]
It would be more clear if the first transaction was marked as failed instead of pending. Initially, we were following up with customers to see what they did that produced a pending result and checking Authorize.Net to see if funds went through. Marking it as failed would at least make it clear that no funds went through. 

A retry should probably not change the history. We still want to see that there was an attempt that failed. It would be a clearer UX to change the error message, in the case that the user hits back, that they should refresh the page before submitting the again.

**Comment by ericnicolaas** [comment]
Good point @rafecolton. So donation becomes **failed**, then if they retry and succeed, it becomes **paid**. If they don't retry, it remains as **failed**.

The donation log should include both status updates.

**Comment by ericnicolaas** [comment]
This is partially fixed. When a donation fails now, Charitable will handle a re-attempt at that donation as exactly that — a re-attempt. Previously it would create a brand new donation, leaving an orphaned "pending" donation when in fact the donor did eventually succeed with the donation.

Updates are still required to this in the individual gateways to make sure that failed payment attempts cause the donation to be marked as failed.
