### ISSUE TITLE
Adding Donation Amounts widget to footer breaks modal donation form

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#174]
Both the widget donation amounts form and the canonical donate form use the same id (`#charitable-donation-form`), so having both on the page or having multiple donation widgets on the page causes some issues.

On pages with a donation modal, because the footer widget appears earlier in the DOM than the modal, the validation and payment method events are applied only to the footer form.  This means that the user cannot select other payment methods in the modal, and the form does a regular submission instead of an ajax submission.  In addition, if there is validation that would prevent the modal form from being submitted (e.g. invalid credit card number), it instead prevents submission of the footer donate amounts form. 

On pages with multiple donation widgets, the initialization process that applies the `selected` class to checked radio buttons only does so for the first instance of the form.

Finally, error messages appear both in the form and in the footer, which is strange UX.

All of these issues stem from using the id as the primary selector, which implies that there will only ever be one of these forms.

**Comment by ericnicolaas** [comment]
@rafecolton I have been testing this but it looks like with the changes in 2b08397 this was resolved. Basically, the donation widget form gets a different ID than the regular donation form. If you do still notice problems with this, please let me know.

**Comment by rafecolton** [comment]
@ericnicolaas if the form has an ID, it still doesn't cover the case where there are two widget forms on the same page.  For example, [this page](https://humanitarian.himalayaninstitute.org/celebrating-10-years-service/) (second form is in the footer).
