### ISSUE TITLE
Clear donation amount from session after successful donation made

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#181]
The donation amount is stored in the session so it can be passed from the amounts form to the donation form.  However, some users found it off-putting to have the amount suggested after the already made a donation.  It would be helpful to have a filter that instructs Charitable to remove the donation amount from the session after a donation is successfully completed.

**Comment by ericnicolaas** [comment]
I don't think we need a filter; this should just happen by default. I'm going to mark this as a bug :)
