### ISSUE TITLE
Error notices should be visible in current viewport

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#183]
When the user encounters an error that results in notices being displayed, the notices should be within the user's current viewport.  Otherwise, it can be confusing UX, as the user has to scroll to determine what happened.

Currently affects notices on the donate page generated by JS, may affect other pages as well.

**Comment by ericnicolaas** [comment]
@rafecolton This should be happening already. Are you using the latest `master`?

**Comment by rafecolton** [comment]
Yes, using the latest master.  It looks like the error notice is getting hidden behind the nav.  I'm guessing this is also an issue for other folks with sticky nav.

**Comment by ericnicolaas** [comment]
Ah, I see. I think that's something that needs to be resolved at the theme level, not within Charitable. The solution is usually to set a higher `z-index` property for the element, but doing this out of the box could also cause the errors to be displayed above things it shouldn't be displayed above, like dropdown menus or things like that.
