### ISSUE TITLE
Charitable & Seamless Donations do not play nice

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#197]
Basically, we're both defining a `donation` post type, which results in the admin Donations page for Seamless Donations not working; it just goes to Charitable's page instead.

**Comment by ericnicolaas** [comment]
Pre-1.4.2, I want to see whether an easy fix is possible for this. Renaming the post type is _not_ easy.

**Comment by helgatheviking** [comment]
Not sure why anyone would be using both, but yeah renaming the post type to something like `charitable_donation` would require a major data upgrade process.

**Comment by ericnicolaas** [comment]
It's a problem for people who have been using Seamless Donations for a while but want to start doing peer to peer fundraising, which isn't possible with SD. Adding a built-in donation/donor/campaign importer would be a good way to help people make that transition. Really not too sure if there is any way to work around this clash of post types.

**Comment by helgatheviking** [comment]
Still doesn't seem like a bug, just a natural consequence of using two donation plugins. The only way would be to change the post type name. I think an importer would be better though possibly more work.

**Comment by ericnicolaas** [comment]
Alright, I've tried a couple things but this is just not going to work without changing the post type.
