### ISSUE TITLE
Add a link to the registration page from the login form

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#204]
This should also pass across the `redirect_to` value if there is one, so that the user is redirected back to where they should be.

**Comment by ericnicolaas** [comment]
We need to update the documentation about the login shortcode since this adds a new shortcode parameter: `show_registration_link`. This expects a simple boolean `true` or `false`. Defaults to `true`. If set to `false`, the link to the registration page will not be displayed.

**Comment by rafecolton** [comment]
The value for `registration_link` should default to `false` so an update to Charitable doesn't make unexpected changes to the login page. This would affect a site that [already has a link like this](https://humanitarian.himalayaninstitute.org/login/) and is using the default login shortcode. Same with #205

**Comment by ericnicolaas** [comment]
@rafecolton I've thought about this, but I'm still inclined to have this on by default. I know that some sites like yours will suddenly have an unnecessary second link added, but for the vast majority of users having this on by default makes the most sense.

To avoid any issues on yours, you can go ahead and add the `registration_link_text` and `login_link_text` parameters to your shortcodes, setting both to `false`.
