### ISSUE TITLE
Campaign Manager role does not do anything

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#209]
If you create a new user and set them up as a campaign manager, you would expect them to be able to create, edit and manage campaigns. 

I also feel like they should also have access to the Donations table.

I would not expect them to manage the Charitable settings though. That still feels like an admin role.

Issue reported in https://wordpress.org/support/topic/user-role-campaign-manager-has-no-access?replies=1

**Comment by rafecolton** [comment]
+1

Agree about access to Donations table and no access to Charitable settings.

We solved this by changing the admin menu capability, but I would prefer more restricted permissions as you describe above.

```php
function ch_admin_menu_capability( $default ) {
  // NOTE: default is manage_options
  return 'manage_charitable_settings';
}

add_filter( 'charitable_admin_menu_capability', 'ch_admin_menu_capability' );
```

**Comment by ericnicolaas** [comment]
Hmm, apparently previously all campaign managers received the exact same caps as the admin:

```
$wp_roles->add_cap( 'campaign_manager', 'view_charitable_sensitive_data' );
$wp_roles->add_cap( 'campaign_manager', 'export_charitable_reports' );
$wp_roles->add_cap( 'campaign_manager', 'manage_charitable_settings' );

$wp_roles->add_cap( 'administrator', 'view_charitable_sensitive_data' );
$wp_roles->add_cap( 'administrator', 'export_charitable_reports' );
$wp_roles->add_cap( 'administrator', 'manage_charitable_settings' );
```
I'm thinking that we'll remove the `manage_charitable_settings` option from campaign managers, and change the permissions on viewing donations and campaigns to `view_charitable_sensitive_data`.

Any changes to this are going to need an upgrade routine (not the end of the world).
