### ISSUE TITLE
Custom tables not created when Charitable is network activated

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#225]
This happens in two ways: 

1. If you network activate Charitable, existing sites do not have the the custom tables created automatically. 
2. When you add a new site on a network with Charitable network activated, the custom tables are not added.

**Comment by helgatheviking** [comment]
[For reference](http://wordpress.stackexchange.com/questions/181141/how-to-run-an-activation-function-when-plugin-is-network-activated-on-multisite)
