### ISSUE TITLE
Use classes for CSS

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#227]
In particular `#charitable-donation-form` is not the ID of a donation form in a widget, so the form isn't displaying the same. 

![image](https://cloud.githubusercontent.com/assets/507025/18524629/c1450fcc-7a7e-11e6-81bc-711ec060e215.png)

Maybe that's intentional, but it doesn't look as nice when used in page builders. 

Relatedly, I'd love the "active" styling to work without JS, but I'm drawing a blank.

**Comment by ericnicolaas** [comment]
For the donation forms, we use `.charitable-donation-form` as a class too. That should be on the widget, the main donation form and also the donation form that is used by Charitable EDD.

**Comment by helgatheviking** [comment]
But the [css](https://github.com/Charitable/Charitable/blob/master/assets/css/scss/public/_forms.scss#L127) is using an ID selector. Full disclosure, I'm inserting the widget via the Beaver Builder page builder, but with a class selector, it'd be styled the same.

**Comment by ericnicolaas** [comment]
Ah gotcha. 

I'm a bit hesitant to switch to using the class for the CSS, because that gives us less control over the display of the output. More likely to have theme styles overriding some of Charitable's styling. 

Not completely closed to the idea, but hesitant.

**Comment by helgatheviking** [comment]
>gives us less control over the display of the output

Not sure I understand what you mean here. Themes aren't any more likely to have `.charitable-donation-form .something {}` in their regular CSS than `#charitable-donation-form .something {}`. Themes will still be able to override styles, and their existing overrides will still work as ID would take precedence over the class rule.

**Comment by rafecolton** [comment]
@ericnicolaas using an ID assumes there will only ever be one donation form on the page, which is a problematic assumption as documented in https://github.com/Charitable/Charitable/issues/174

👍 for using classes

**Comment by ericnicolaas** [comment]
@helgatheviking Themes aren't likely to have `.charitable-donation-form ul {}` in their regular CSS, but this kind of thing _is_ common: `#main ul`.

If Charitable defines `#charitable-donation-form ul`, that should override `#main ul`; `.charitable-donation-form ul` doesn't override `#main ul`. 

Believe me, I much prefer writing CSS that's based around classes, but let's just say I'd want to spend a _lot_ of time testing CSS changes that can result in donation forms looking sub-par.

@rafecolton I believe #174 is closed, as the ID of the widget donation form was changed.

All that being said, I have just pushed up a couple commits that fix the styling for the widget (basically by targeting the ID of the widget form as well as the ID of the regular donation form). @helgatheviking Can you see if this fixes the styling of the widget for you?

**Comment by helgatheviking** [comment]
`.charitable-donation-form ul` does override `#main ul` even if `.charitable-donation-form ul` comes earlier than `#main ul`. See this [example](https://jsfiddle.net/arnjnq9b/1/)

If you want to be even more specific we could use:
`.charitable-donation-form ul.donation-amounts`

**Comment by ericnicolaas** [comment]
@helgatheviking Circling back around to this. I tried out your PR #273. It works fine on some themes, but as soon as the theme uses an ID selector, we end up with issues. 

Here's an example from Divi. The first screenshot shows how it looks with the ID selector:

<img width="730" alt="screenshot 2017-01-06 15 25 59" src="https://cloud.githubusercontent.com/assets/676582/21707575/762cf31a-d424-11e6-9e69-43fb17e609a7.png">

Next, the class selector:

<img width="939" alt="screenshot 2017-01-06 15 24 43" src="https://cloud.githubusercontent.com/assets/676582/21707574/740edd3c-d424-11e6-9e2f-c024c7a8d4a3.png">
 
Note the extra padding to the left and below, which is because of Divi's `#left-area ul` rule. I tried countering this with an obscenely long string of classes, which you can see in the inspector on the side, but it still fails to trump that one Divi rule.

**Comment by ericnicolaas** [comment]
Going to close this as wontfix for now as this is going to be too hard while trying to maintain decent compatibility with themes.

**Comment by helgatheviking** [comment]
I hate Divi. But how did we leave this in workers and page builders? Most of the styles could be class based and just that ul could keep the ID to counter the left indent.
