### ISSUE TITLE
Add a [charitable_stat] shortcode

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#23]

**Comment by ericnicolaas** [comment]
I'm leaving this as an issue, but will not assign a milestone since no one is asking for this.

**Comment by ericnicolaas** [comment]
Some thoughts on features: 

- Show totals of all campaigns by default.
- Limit to just show totals of certain campaigns with a parameter. 
- Show donor count instead of amount raised.
- Add possibility to show total amount as a percentage of a custom goal.

Possible implementation:
```
\\ Default. Show total $ raised in all campaigns.
[charitable_stat]

\\ Same as default. Shows total $ raised in all campaigns.
[charitable_stat display=total]

\\ Show total number of donors in all campaigns.
[charitable_stat display=donors]

\\ Show total number of donations in all campaigns.
[charitable_stat display=donations]

\\ Show total $ raised in a specific campaign.
[charitable_stat campaigns=id]

\\ Show total $ raised in a set of campaigns.
[charitable_stat campaigns=id1,id2,id3]

\\ Show number of donors to a set of campaigns.
[charitable_stat campaign=id1,id2,id3 display=donors]

\\ Show number of donations for a set of campaigns.
[charitable_stat campaign=id1,id2,id3 display=donations]
```

**Comment by dchymko** [comment]
A charity I'm working with wanted to be able to display the total raised on custom pages so I've added a shortcode to do the 1st one in the list.

I used minimal formatting so that the shortcode could be used like :

> Hooray team, we've raised [charitable_stat] across all campaigns so far!

Might add a few more of the implementations in before PRing tomorrow

**Comment by ericnicolaas** [comment]
Nice! That example you've given of the "Hooray team..." text is exactly how I see this being useful. The output should be pretty much without any extra HTML markup — _maybe_ a <span> with a class, but not even sure if that is necessary. 

Looking forward to that PR :)

**Comment by ericnicolaas** [comment]
@dchymko I know it's been a long time, but just wondering if you would still be interested in contributing your work on this shortcode as a PR?

**Comment by dchymko** [comment]
Hey, yeah, i'd love to look at this but not sure if I'll have the time right now :(

**Comment by ericnicolaas** [comment]
I made https://github.com/Charitable/Charitable-Stat-Shortcode, which is basically a standalone plugin that implements all the above. Still intend to merge this into core in 1.6, but at least we have a solution available for people now.
