### ISSUE TITLE
Add a notice to the donation form when Test Mode is enabled

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#233]

**Comment by helgatheviking** [comment]
This looks like it has been completed:

![image](https://cloud.githubusercontent.com/assets/507025/19163436/946018d6-8bc1-11e6-8bfc-a815130b7fc6.png)

**Comment by helgatheviking** [comment]
I think this was closed by https://github.com/Charitable/Charitable/pull/250

**Comment by ericnicolaas** [comment]
Correct
