### ISSUE TITLE
Custom triggers in update_status() method

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#247]
What if we called a custom trigger in [`update_status()`](https://github.com/Charitable/Charitable/blob/master/includes/donations/abstract-charitable-donation.php#L575) and used that to launch the emails via the [email hooks](https://github.com/charitable/Charitable/blob/master/includes/emails/charitable-email-hooks.php#L34-L39)

so that we did not have to check the campaign donations [here[(https://github.com/Charitable/Charitable/blob/master/includes/emails/class-charitable-email-donation-receipt.php#L80) because the email would never fire on `wp_insert_post()` via the default post transition hooks?

**Comment by ericnicolaas** [comment]
@helgatheviking Is there still any need for this, or have we solved this in other ways? Struggling to remember the context and purpose of this one.

**Comment by helgatheviking** [comment]
I think the goal was really easy/obvious triggers for other actions, especially emails. for example: `charitable_donation_complete` could trigger the completed email and `charitable_donation_failed` could trigger the failed email, etc. Maybe it isn't necessary, but it seemed like a good idea at the time.
