### ISSUE TITLE
Add custom bulk actions for Donations table (WordPress 4.7 method)

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#251]
We already have custom bulk actions added to the Donations table, using a hacky method. As of WordPress 4.7, it should be much easier to do this, and in a cleaner way: 

https://make.wordpress.org/core/2016/10/04/custom-bulk-actions/

Backwards compatibility needs to be maintained (i.e. we need to support WordPress < 4.7), but would be good to take full advantage of this for anyone using WP 4.7 or greater.

**Comment by helgatheviking** [comment]
🎆
