### ISSUE TITLE
Welcome Page shouldn't include Password Reset email

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#252]
When you first activate Charitable, you are redirected to the welcome page, which has a checklist to make sure you enable a payment gateway, create a campaign and activate emails. The first two are fine, but for the emails it's picking up that the Password Reset email is activated and listing that as a "done" checklist item; password reset should be filtered out of this page.

**Comment by admah** [comment]
Just added a PR to take care of this issue.

**Comment by ericnicolaas** [comment]
Closed by #254
