### ISSUE TITLE
Picture field is not usable on mobile

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#259]
Adding a new photo to the picture field works fine from mobile, but replacing or removing an existing image is impossible; the Remove button is underneath the image preview and cannot be clicked.

**Comment by bSzala** [comment]
Hey, I installed the plugin yesterday, but to be honest, I don't know where I can find the feature You writing about. Can You describe a little better how Can I reproduce this bug from the fresh installed version.

**Comment by ericnicolaas** [comment]
@bSzala The picture field is currently only used when you have the User Avatar or Ambassadors extensions installed.

**Comment by ericnicolaas** [comment]
This is working now for me in Android. Closing this, but there is still a problem with Mobile Safari, noted in #370
