### ISSUE TITLE
Donation Reports

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#265]
Would be sweet to add some graphs showing how much has been donated. For example:

![image](https://cloud.githubusercontent.com/assets/507025/19464244/3b6cc9ba-94c0-11e6-8f7c-104f0d35c65f.png)

**Comment by ericnicolaas** [comment]
I'm putting this as add-on territory for now, though I'm open to reconsidering that in the future.

**Comment by ericnicolaas** [comment]
Closing this in favour of #355.
