### ISSUE TITLE
Suggestion. Public list of donors and donations.

### ISSUE THREAD

**Issue by ruayrod** [Charitable/Charitable#267]
A picture is worth a thousand words:
http://www.jovenfutura.org/recaudacion-recurso-ibi/

Currently this list we do it by hand.
In this list the initials of the donors appear due to data protection laws.

**Comment by ericnicolaas** [comment]
You can use the Donors widget for this. It won't display in a table like this by default, but you could customize the output by overriding the `charitable/templates/widgets/donors.php` template in your theme.
