### ISSUE TITLE
Automatically refund donations in the gateway

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#269]
Currently, if you need to refund a donation, you would need to do it through the payment gateway. The donation will then be marked as refunded within Charitable, but it would be nice if people could instead refund directly from Charitable. If you change a donation to Refunded, there should be an option to refund it in the payment gateway too.

**Comment by helgatheviking** [comment]
+1 Being able to change status from the dashboard will be relevant to Recurring too.
