### ISSUE TITLE
A way to hide Excerpts on campaign page

### ISSUE THREAD

**Issue by iamkarsoft** [Charitable/Charitable#277]
Would like a way to hide the excerpts of a campaign to make use of the read more button.  This will also ensure that the template is clean and doesn't break as some campaign have longer description than others, and when excerpts are shown , the design becomes inconsistent when using the campaign shortcodes .

**Comment by ericnicolaas** [comment]
Sorry for taking so long to get around to this @iamkarsoft. 

It's possible to hide the excerpt with a little bit of custom code:

```
function ed_unhook_default_template_functions() {
    remove_action( 'charitable_campaign_content_loop_after', 'charitable_template_campaign_description', 4 );
}

add_action( 'after_setup_theme', 'ed_unhook_default_template_functions', 11 ); 
```
