### ISSUE TITLE
"Group by..." option in Donors widget has unexpected results

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#286]
There is an issue with the way the "Group by..." option works in the Donors widget. 

Basically, it will group donations that belong to the same donor ID. This makes sense. 

However, if you are a site admin and you want to add multiple donations for people who donated offline, the current process is to do that through the Offline payment method. If you are logged in while doing this, all those payments will be associated with your donor account, _even if_ you have provided a different email address for the donor. 

Solving #241 will mitigate this issue somewhat, since then people can create donations via the dashboard. Question is: Is that enough of a solution?

Realistically, if an ordinary person (not the site admin) is logged in and makes a new donation with a different email address, should that donation be associated with the same donor record, or with a different donor record? 

Open for discussion :)

**Comment by darrellrnelson** [comment]
Unless you force a user to login this would be easily remedied but may cause 50% or higher of the donors to abandon the donation.  
I would code it to check to see if the FIRSTNAME, LASTNAME, EMAIL or ADDRESS match.  If they do combine donations.

**Comment by darrellrnelson** [comment]
Adding OFFLINE donations is the 'norm' with services such as classy.org and others.  It would be GREAT to be able to add an offline donation in the 'donors' panel in the wp-admin.  That way it doesn't matter if we are using Charitable or Charitable Digital Downloads we could manage offline donations.   In our experience using Classy was more than 70% of our campaigns comprised of offline donations and we still want to SEE the fundraising bar GROW!...
Thus you should also consider adding under the donor options "PLEDGE" so the fundraising bar will still show the growth... but we know on our side the funds are still coming.  Thanks all.

**Comment by darrellrnelson** [comment]
In the mean time: maybe include some content to let the Charitable users if they add OFFLINE donations they should clear their cache each time they do.  Maybe that will ensure each donor doesn't share the same donation grouping?

**Comment by ericnicolaas** [comment]
After closing #222, #385 and #409, this is not longer an issue as far as I can tell. What happens now is that whenever you donate with a different email address, a new donor record is created. If you are logged in, this means there can be multiple records associated with your `user_id` but in the donor count and donors widget, it will count each one separately.
