### ISSUE TITLE
Charitable Slack Addon

### ISSUE THREAD

**Issue by ramiy** [Charitable/Charitable#290]
I'm working on a new Slack addon for Charitable. My question is **what is the name of the action that is fired up after a new donation is made?**

The idea is to hook to that action and send a notification to slack with each donation.

![screenshote-1](https://cloud.githubusercontent.com/assets/576623/21874049/2ff0feea-d87b-11e6-96cc-e462787a791d.png)

**Comment by ramiy** [comment]
This is how the final result should look like:

![screenshote-2](https://cloud.githubusercontent.com/assets/576623/21874417/7bdb28b0-d87d-11e6-9b19-18beb545360c.png)

**Comment by ericnicolaas** [comment]
@ramiy: There are a few hooks, but two that would be a good option:

`charitable_after_save_donation` is fired after the donation is saved to the database. Gateway processing has not been done yet, so the donation still has a status of Pending. 

`charitable-completed_donation` is fired when the donation is marked as Paid. For donations made through PayPal, Stripe, etc, this should happen pretty much straight away, unless the payment fails or is canceled. With the Offline gateway, this hook is not fired until an admin manually marks the donation as Paid.

Given the caveat of the Offline donations, you might want to use a combination of the two hooks (i.e. use `charitable_after_save_donation` for Offline donations, and `charitable-completed_donation` for everything else).

**Comment by ramiy** [comment]
@ericnicolaas Where is this filter located in the code? Can't find it. Probably it's a dynamic filter.

**Comment by ericnicolaas** [comment]
`charitable-completed_donation` comes from `wp_transition_post_status()`. 

`charitable_after_save_donation` is here: https://github.com/Charitable/Charitable/blob/master/includes/donations/class-charitable-donation-processor.php#L433

**Comment by ramiy** [comment]
Do you have examples where you use `charitable-completed_donation` ?

**Comment by ericnicolaas** [comment]
@ramiy The only point at which it's used currently is with the email sending: https://github.com/Charitable/Charitable/blob/master/includes/emails/charitable-email-hooks.php#L31-L37

**Comment by ramiy** [comment]
Done!

https://wpPlugins.io/downloads/charitable-slack/
