### ISSUE TITLE
Customize form-donation.php

### ISSUE THREAD

**Issue by franc3s** [Charitable/Charitable#296]
Hello,

I’m trying to add a privacy disclaimer in the donation form page. I use Reach theme so I created “form-donation.php” inside the new folder charitable/templates/donation-form of my Reach Child Theme.

I know the file “form-donation.php” is correct to add this text before I tried it into the main plugin folder, but I can’t understand why the website is not displaying the edit I made in the child file.

I already use with success the folder reach-child-theme/charitable for other customization…. so…. what could be the problem? help!

Thanks in advance

**Comment by ericnicolaas** [comment]
@franc3s It should be saved in your theme to charitable/donation-form/form-donation.php -- remove the templates part.
