### ISSUE TITLE
WP Admin Campaign Short Description not matching front end edit data.

### ISSUE THREAD

**Issue by rybridge** [Charitable/Charitable#304]
Just getting started working with Charitable and noticed something odd with the short descriptions of a campaign.

If you add a campaign via the WP Admin create campaign method and set a short description, when the user edits their campaign the data in the Short Description box seems to not match what the Wordpress admin shows.

#### Adding A Campaign via WP
![create-campaign](https://cloud.githubusercontent.com/assets/419370/23229909/a67617ec-f907-11e6-9d29-91e7df84af87.gif)

#### Viewing and editing campaign on front end
![view-edit](https://cloud.githubusercontent.com/assets/419370/23229987/e7324d5a-f907-11e6-9e4d-e00346f37efc.gif)

Notice that the short description is blank when it should be "This is my description".

#### Saving on Front End
![update short desc](https://cloud.githubusercontent.com/assets/419370/23230123/540edc68-f908-11e6-96bc-56ff2088940c.gif)

#### Editing via WP Admin again (shows updated front end data)
![edit_campaign_ _chainbreaker_ _wordpress](https://cloud.githubusercontent.com/assets/419370/23230136/63eee65a-f908-11e6-97c5-8037164722e9.png)

**Comment by rybridge** [comment]
Ran this post by a co-worker and he didn't fully understand what I was getting at so I worked through some clarification with him.

* If you put in a short description in the wp admin
* Then view the campaign you can see it, but if you edit it via the front end editor the short description isn’t there to edit
* You can add a new short description via the front end editor and it’ll take and update the post and show the new data when editing the campaign via WP Admin
* But anytime you make an edit to the short description in wp admin that change won’t show when editing on the front end

Hope that helps clarify it a bit more.

**Comment by ericnicolaas** [comment]
Nice catch @rybridge! Looks like this is a bug on the Ambassadors side of things, so I'll make sure we fix it up in there.

**Comment by ericnicolaas** [comment]
p.s. Do you have a BitBucket account? I'd love to add you as a participant on our Ambassadors repo, which is private.

**Comment by ericnicolaas** [comment]
Just pushed out an update to Ambassadors which fixes this.

**Comment by rybridge** [comment]
Awesome, thanks much! My bitbucket account email is ryan@softwareforgood.com
