### ISSUE TITLE
Creating campaign via wp_insert_post needs additional meta

### ISSUE THREAD

**Issue by rybridge** [Charitable/Charitable#307]
We're working on a way to create fundraising for users after they've checked out via WooCommerce and using `wp_insert_post` but we noticed that once the campaign was created that the data was fine, but the donation amount field wasn't showing up on the donation form. We discovered that there is an additional meta field that needed to be set, that field is `_campaign_allow_custom_donations`

We were looking at this test as an example. https://github.com/Charitable/Charitable/blob/master/tests/helpers/charitable-campaign-helper.php#L29-L60

It might be helpful for others down the road if that was added to that test or docs somewhere.

Our solution was just setting it to true so that any donation could be entered. `update_post_meta( $campaign_id, '_campaign_allow_custom_donations', 1);`

This isn't a huge issue, but thought I'd point that out if anyone else runs into this.

**Comment by rybridge** [comment]
Let me know if this isn't the proper forum for stuff like this and I can submit it elsewhere.

**Comment by ericnicolaas** [comment]
Hey @rybridge sorry for never responding to this! Good point re. the unit testing helper not including that. I'll go ahead and include it in the test. At some point we need to greatly improve our developer documentation, but for now that will serve as a decent reference point.

**Comment by ericnicolaas** [comment]
Closed in dd3f78e287f762f6f474c143f6af058503c6ce66
