### ISSUE TITLE
Allow campaign creator to preview own campaigns

### ISSUE THREAD

**Issue by ajien** [Charitable/Charitable#318]
Non-admin campaign creators should be allowed to preview their own campaigns.

**Comment by ericnicolaas** [comment]
If the user is logged in, they should be able to preview their campaigns already. Are you using Ambassadors?

**Comment by ajien** [comment]
Yes, using Ambassadors. I am getting 404 when trying to preview campaign as a campaign creator (currently logged in).

**Comment by ajien** [comment]
I found my mistake. I set new user registrations to donor and not campaign creator. Now I would want to give campaign creators the ability to delete campaigns.

**Comment by ericnicolaas** [comment]
@ajien That's not possible at the moment. It is something we have planned for a future version, but for now all campaigns have to be deleted via the admin.
