### ISSUE TITLE
Add email shortcode for offline donation instructions

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#324]
If someone donates offline and they get an email with their receipt, it could be helpful to again give them the offline donation instructions. This is particularly useful when #33 is implemented.

**Comment by ericnicolaas** [comment]
In the interim, https://github.com/Charitable/library/blob/master/emails/add-offline-instructions-field.php achieves this.

**Comment by helgatheviking** [comment]
It seems like they ought not get a receipt? They ought to get the instructions and get the receipt when completed?

**Comment by ericnicolaas** [comment]
I believe this should be closed. Dropping to 1.5.10 to make sure we review this.
