### ISSUE TITLE
Display username in [charitable_profile] output

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#325]
After you register, there is not a way to see what your username is at the moment.

**Comment by ericnicolaas** [comment]
@wesfranklin I'm not sure how to include this. Really basic idea is to just show it at the top as a bit of text. Any thoughts on that?

![screenshot 2017-12-11 16 10 37](https://user-images.githubusercontent.com/676582/33818697-ea0e0a66-de8d-11e7-8ef7-9c514bc6863a.png)

![screenshot 2017-12-11 16 11 06](https://user-images.githubusercontent.com/676582/33818699-eb5e72de-de8d-11e7-97e9-3126623c4091.png)

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah that works. Second one is more obvious.
