### ISSUE TITLE
Donation Notification - campaign_creator returning incorrectly

### ISSUE THREAD

**Issue by rybridge** [Charitable/Charitable#333]
We've been scratching our head on this one for awhile now, and I think we have it locked down to how it is happening.

We’ve been seeing a number of instances where when someone receives a donation, and they get their “New Donation Notification” email that the `[charitable_email show=campaign_creator]` will return the name of a donor, and not the creator(email recipients) name.

We’ve done some digging on this and it seems to happen when a user is logged in and has a friend donate to them on the logged in user’s computer/tablet and use a different name than the logged in user. It has been common with husband/wife situations. It just seems to be preferring the donor first/lastname for `[charitable_email show=campaign_creator]` vs the proper campaign creator.

#### Screenshots
![another_email_mystery](https://cloud.githubusercontent.com/assets/419370/26072862/b3b36f30-3972-11e7-957d-e79fc5964029.png)

![slack_-_software_for_good](https://cloud.githubusercontent.com/assets/419370/26072775/70fcc678-3972-11e7-9fd5-7520f525e350.png)

0. Have a member account, and have not made any donation yet.
1. Log in a user A with first_name and last_name in your profile.
2. Donate to a campaign created by user B (or possibly even yourself), but entering a *different* donor name.
    - Now `wp_charitable_donors` has a record with user A's `user_id` and the donor name.
3. Log out
4. Make a donation to user A's campaign as another user or an anonymous visitor.
    - The Charitable_Ambassadors_Email_Creator_Donation_Notification email content will use the donor name for `campaign_creator`.

**Comment by ericnicolaas** [comment]
Thanks for the heads-up on this @rybridge! I've seen this issue with the email address before and fixed that in a new version a few weeks ago, so it looks like this is stemming from the same basic problem. I am making an issue for this in the private Ambassadors repo.

**Comment by ericnicolaas** [comment]
Just a heads-up that a fix for this is coming in version 1.1.15, which I hope to have released today or early next week.
