### ISSUE TITLE
see donation promises (offline payments) in campaign widgets

### ISSUE THREAD

**Issue by altatof** [Charitable/Charitable#34]
add an option in the campaign widget and campaign page to see pending payments (donation promises). 
maybe the progress bar should have two colors, one for the actual payments and one for all payments including pending ones.
also show pending payments total in campaign pages.

**Comment by ericnicolaas** [comment]
@altatof 

Could you describe the use-case for showing pending payments? When would it make sense to show that information publicly? 

Cheers, 
Eric

**Comment by altatof** [comment]
consider the offline payments as promises : 

my use-case : all payments are offline ! 

The contributors promise to contribute to fund a software module, and are billed later when the module development starts or ends (or both). 

If you dont show the amount of the "promised" contributions, nobody knows that they exist and we think nobody is interested in this campaign. 

And i guess that showing already funded amounts encourage other to make donations, even if the funds are not already paid.

**Comment by ericnicolaas** [comment]
@altatof 

One way you can get around this right now is by including the Pending status as one of the approval statuses. See https://github.com/Charitable/library/blob/master/donations/add-pending-to-approved-statuses.php for a code snippet you can use to set that up. 

Cheers, 
Eric

**Comment by ericnicolaas** [comment]
@altatof 

As for building this into the plugin, I think that the idea of "promised" contributions maybe ties into pre-approved payments (i.d. donations that people make through a gateway like Stripe, but are not charged for until a set time in the future, like when the campaign is finished). 

I will circle back to this idea when I am building out that functionality.

**Comment by altatof** [comment]
@ericnicolaas :+1: code snippets are cool, i haven't see this library folder before.

**Comment by altatof** [comment]
you are right, pre-approved payments and payment promises seem to be tied (hope i dont make too much misunderstandings with my approximative english)

anyway, the code snippet you wrote seems to be good enough for my use-case at the moment.

**Comment by ericnicolaas** [comment]
Glad the code snippet helps out. We haven't really publicised the library
before, but really should... it has a bunch of handy little tweaks in
there.

Soon we will have pre-approved payments support for Stripe, which might
suit you even better than the offline payments option.

Cheers,
Eric

On Fri, Nov 6, 2015 at 6:50 PM altairis <notifications@github.com> wrote:

> you are right, pre-approved payments and payment promises seem to be tied
> (hope i dont make too much misunderstandings with my approximative english)
>
> anyway, the code snippet you wrote seems to be good enough for my use-case
> at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Charitable/Charitable/issues/34#issuecomment-154352553>
> .
>
-- 


*Eric Daams*Co-creator of Charitable

wpcharitable.com
twitter.com/wpcharitable

The fundraising alternative for non-profits.
Powered by WordPress.

**Comment by ElStupid** [comment]
Second that, I have the same use-case as altatof.
Will use the snippet for now, thanks!

**Comment by ericnicolaas** [comment]
I'm going to close this as I think it's something that should be part of an extension in the future; not a core feature.
