### ISSUE TITLE
Provide a link back to the parent settings pages from sub-settings

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#351]
When you are editing an email or a particular gateway's settings, there should be a link back to the parent settings page. Obviously this can be clicked from the top-level tabs, but that seems a little less obvious to me.

**Comment by ericnicolaas** [comment]
Fairly easily done: 

**Gateways**
![screenshot 2017-07-05 13 54 43](https://user-images.githubusercontent.com/676582/27849105-887874b6-6189-11e7-9b05-19d9c6939460.png)

**Emails**
![screenshot 2017-07-05 13 53 50](https://user-images.githubusercontent.com/676582/27849084-6a4ca778-6189-11e7-97ff-74e70197c561.png)

**Newsletter Providers**
![screenshot 2017-07-05 13 53 04](https://user-images.githubusercontent.com/676582/27849067-4907b51c-6189-11e7-97a8-0fd711891445.png)

@wesfranklin What do you think of the styling here?

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah looks fine.
