### ISSUE TITLE
Feature request: improve display on the campaigns page

### ISSUE THREAD

**Issue by altatof** [Charitable/Charitable#36]
On a campaign page, if you click on "Campaigns" in the breadcrumbs, the look of the list is not very appealing; it should be more like the campaigns widget
![campaigns page](https://cloud.githubusercontent.com/assets/396322/10939520/79fe28f2-8302-11e5-96e9-7f9aa0209a82.png)

**Comment by ericnicolaas** [comment]
Agreed. This is what #18 is set to improve.

**Comment by ericnicolaas** [comment]
We have actually disabled the campaigns archive by default (as of `1.3.0` I think), so this is no longer an issue.
