### ISSUE TITLE
Send email notification to admin when a new user registers

### ISSUE THREAD

**Issue by altatof** [Charitable/Charitable#37]
when a donator register, a wp user is created but no notification email is send to the wp admin.
i have skirted the problem using the "charitable_after_insert_user" hook in my functions.php theme file (code below) but i think it should be integrated in the core.
<code>
add_action('charitable_after_insert_user', 'notify_new_user', 10, 2);
function notify_new_user($user_id, $values)
{
    wp_new_user_notification( $user_id, null, 'admin' );
}
</code>

**Comment by ericnicolaas** [comment]
I think this makes sense, but need to consider the situations in which donors are added as registered users before pushing this.

**Comment by altatof** [comment]
may i PR my code snippet in your library folder ?

**Comment by ericnicolaas** [comment]
Absolutely!

On Fri, Nov 6, 2015 at 6:36 PM altairis <notifications@github.com> wrote:

> may i PR my code snippet in your library folder ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Charitable/Charitable/issues/37#issuecomment-154350268>
> .
>
-- 


*Eric Daams*Co-creator of Charitable

wpcharitable.com
twitter.com/wpcharitable

The fundraising alternative for non-profits.
Powered by WordPress.

**Comment by ericnicolaas** [comment]
Pushing this back. No one has really asked for this, so not sure whether to worry about integrating this. Might be better to just provide a snippet of code people can use to handle this.

**Comment by ericnicolaas** [comment]
Closing this as the code snippet should suffice: https://github.com/Charitable/library/blob/master/registration-form/send-new-user-notifications.php
