### ISSUE TITLE
Forgot Password endpoint shows login form

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#377]

**Comment by yavisht** [comment]
forgot-password endpoint also points to the default page template and not the page template that's assigned to the login page.

**Comment by yavisht** [comment]
This is how I fixed my problem for now.

`
<?php

$catch_forgot_password = $_SERVER[REQUEST_URI];

if (strpos($catch_forgot_password, 'forgot-password') !== false) {
	echo '<div class="page-template-user-dashboard">';
		include 'user-dashboard.php';
	echo '</div>';
	exit;
}

?>
`

**Comment by ericnicolaas** [comment]
Good catch @yavisht! I'll make a new issue for this.
