### ISSUE TITLE
Permission denied when exporting Recurring Donations 

### ISSUE THREAD

**Issue by yavisht** [Charitable/Charitable#386]
Getting "Sorry, you are not allowed to access this page." error when trying to export recurring donations.

**Comment by ericnicolaas** [comment]
@yavisht Do you get this error when exporting regular donations?

**Comment by yavisht** [comment]
@ericnicolaas no errors exporting regular donations.

**Comment by ericnicolaas** [comment]
OK, thanks for reporting @yavisht. I'm going to add this to the Recurring Donations repo as an issue. Closing it here but rest assured it will get looked at.

**Comment by yavisht** [comment]
@ericnicolaas  thank you!
