### ISSUE TITLE
Fatal Error on Relevanssi build index

### ISSUE THREAD

**Issue by yavisht** [Charitable/Charitable#397]
Not sure what this has to do with Relevanssi build search index. 

`Class 'Charitable_Ambassadors_Template' not found in /app/public/wp-content/plugins/charitable-ambassadors/includes/charitable-ambassadors-core-functions.php on line 43`

**See below**

![screen shot 2017-09-08 at 10 18 19 am](https://user-images.githubusercontent.com/6112201/30190952-19c0d48e-9481-11e7-9789-ac941f77196b.png)
![screen shot 2017-09-08 at 10 17 59 am](https://user-images.githubusercontent.com/6112201/30190951-19be5a9c-9481-11e7-93fe-5ede45b074a5.png)

**Comment by ericnicolaas** [comment]
@yavisht Thanks for reporting this. It looks like Relevanssi must be attempting to actually render/output the content of the shortcode during its indexing, which causes this error. We've had similar issues with Divi. 

I've never really used Relevanssi before. Was this with the free version or one of their upgrades?

**Comment by yavisht** [comment]
@ericnicolaas,

Yes, it is the free plugin. I haven't tested charitable with other indexing plugins yet.

Link : https://wordpress.org/plugins/relevanssi/

**Comment by yavisht** [comment]
@ericnicolaas is there any way to fix this issue? any help appreciated.

**Comment by ericnicolaas** [comment]
@yavisht There is a fix for this coming in Charitable 1.5.4 and Ambassadors 1.1.17 (both updates are needed to fix all the errors with Relevanssi).

**Comment by yavisht** [comment]
@ericnicolaas thanks for the update! cheers :)
