### ISSUE TITLE
Remove deprecated PayPal variables

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#413]
As per https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#deprecated-variables the following variables are deprecated:

- [x] cbt
- [x] no_note

We should remove these.

**Comment by bscottx** [comment]
I can take this on, seems simple & straightforward.

It looks like changes for these only need made in:
`includes/admin/views/settings/paypal-sandbox-test.php`
& `includes/gateways/class-charitable-gateway-paypal.php`

**Comment by ericnicolaas** [comment]
Thanks @bscottx! I'll check your PR and see what impact removing the defaults has.
