### ISSUE TITLE
Display more helpful information in Campaigns table

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#417]
The Campaigns table is not tailored to campaigns.

![screenshot 2017-10-05 14 24 15](https://user-images.githubusercontent.com/676582/31211529-f435eb6a-a9d8-11e7-807f-550bf5d696eb.png)

We should add a campaign's amount raised and end date, as well as a nice, colour-coded status — active, pending, finished, etc.

**Comment by ericnicolaas** [comment]
Early draft:

![screenshot 2017-10-05 15 32 46](https://user-images.githubusercontent.com/676582/31212895-7ce1906e-a9e2-11e7-98f1-69dd7a11d34a.png)

@wesfranklin Can you suggest some alternative colours for finished campaigns? Potentially we could show these as Successful & Unsuccessful for campaigns with goals, and Finished for campaigns without goals.

**Comment by wesfranklin** [comment]
@ericnicolaas What about:
Active: Orange
Finished: Blue
Successful: Green
Unsuccessful: Red

**Comment by ericnicolaas** [comment]
@wesfranklin See below:

![screenshot 2017-10-05 16 14 11](https://user-images.githubusercontent.com/676582/31213972-41dcbdf8-a9e8-11e7-8f8b-96a6720a0d06.png)

I'm a little troubled when comparing these colours with the donation ones:

![screenshot 2017-10-05 16 12 05](https://user-images.githubusercontent.com/676582/31213905-f9cfaebc-a9e7-11e7-9031-7765f0fa00f8.png)

- Orange -> Active campaign & Failed donation
- Blue -> Finished campaign & Refunded donation
- Green -> Successful campaign & Completed donation (this one's not so bad)
- Red -> Unsuccessful campaign & Cancelled donation (also not so bad)

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah, I see what you mean.
What if Active was black and Finished was a lime green?

**Comment by ericnicolaas** [comment]
@wesfranklin OK, so then we would have:

- Orange -> Failed donation
- Blue -> Finished campaign & Refunded donation
- Green -> Completed donation
- Red -> Unsuccessful campaign & Cancelled donation
- Lime green -> Successful campaign
- Black -> Active campaign

With the Lime green, why would we not use the other Green for this? Could you give me a hex code for this so I can test it out and attach a screenshot?

**Comment by wesfranklin** [comment]
I guess you could use the same green, but then it might be confusing?
What about #34d058

**Comment by ericnicolaas** [comment]
@wesfranklin Here we are:

<img width="860" alt="screenshot 2017-10-12 21 07 39" src="https://user-images.githubusercontent.com/676582/31494192-645928c2-af91-11e7-93f6-aca2e0ea94c1.png">

I don't think it would be too big a deal having the same green used here as for the completed donations. I do like this shade of green though. Maybe we should use that for the donations too?

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah that green in nicer, use that for donations too.
