### ISSUE TITLE
GDPR: Add "Stay in Touch" section to donation form with opt-in

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#420]
This will have a big impact on any EU-based organizations:

- https://www.institute-of-fundraising.org.uk/library/gdpr-the-essentials-for-fundraising-organisations/
- https://ico.org.uk/for-organisations/marketing
- https://www.theguardian.com/voluntary-sector-network/2017/may/05/gdpr-charities-prepare-eu-data-protection-changes-consent-fundraising

I'm not sure how much Charitable needs to do here, but at the very least it seems like we should be providing an opt-in/opt-out in the donation form for donors to choose whether they are happy to be contacted.

We should also provide a report that organizations can use to download all data held about a particular donor, and provide an easy way to remove this data.

## Update (April 12, 2018)

This issue refers primarily to providing an opt-in with the donation form that allows donors to choose whether they would like the organization to contact them in the future. 

GDPR compliance covers a broader range of issues (see https://github.com/Charitable/Charitable/issues/550, https://github.com/Charitable/Charitable/issues/551 and https://github.com/Charitable/Charitable/issues/547). I have updated this issue's title to clarify its focus.

At this point I'm undecided on whether this "Stay in Touch" box should be integrated into core, whether we should stick it in a new add-on, or whether it should go into Newsletter Connect.

**Comment by mgab71** [comment]
Hi there, 

Just seconding this, all donate forms should be providing an opt-in/opt-out in order for donors to give their consent to various methods of communication for marketing. A report for organisations to download donor data would also be useful. 

A field would also need to be added in the personal details section of the form for their telephone number. With the opt-in/opt out/consent section, the text needs to be easily editable to allow non-profits to link to their own privacy/data protection policy and reassure donors that their details will not be passed on to third parties. Please see the screenshots below from compliant organisations for further info:

![mariecurie](https://user-images.githubusercontent.com/32675854/31389512-1df953ee-adc9-11e7-910f-bd4b329aa9af.png)

![img_6622](https://user-images.githubusercontent.com/32675854/31389541-37040000-adc9-11e7-8e69-0144587f55d0.PNG)

To refer to further required  functionality, please see below for further reference:

- [https://www.womankind.org.uk/support-us/donate/one-off-gift?title=Help%20us%20do%20more&amount=5](url)
- [https://www.mariecurie.org.uk/donate/directdebit-onestep?amount=5#l6EX01jXHvK2CDjK.97](url)

**Comment by ericnicolaas** [comment]
Thanks @mgab71 those links are very helpful.

**Comment by ericnicolaas** [comment]
https://www.gdprwp.com looks promising.

**Comment by ericnicolaas** [comment]
Also in GDPR:

- https://github.com/Charitable/Charitable/issues/550
- https://github.com/Charitable/Charitable/issues/551

I'm undecided about the scope of this issue. Specifically, it's covering the need for donors to opt-in if they want site owners to stay in touch via email, phone, etc. However, this is not something we currently do in Charitable. We don't provide any tools for emailing or calling donors. Site owners can download an export of their donations and use those email addresses & phone numbers to follow up with donors, but it's not something we control.

That said, adding this as an optional section to the donation form could be a nice bonus feature for Charitable users. It allows them to collect a list of donors that they can contact via phone/email for follow-up marketing, etc. We could tie this into a Donors export tool so site owners can grab a list of donors, with a column specifying whether they prefer to be contacted.

**Comment by mgab71** [comment]
Hi @ericnicolaas, 

This will need to be added to the plugin before 25 May. Could you confirm if this update would be available before then? This approach sounds good, so long as all of the contact methods are available as outlined above in the screen shot within the optional section. Then if donors do not fill that out, they haven't opted in and we cannot contact them.

Thanks, 

Miranda

**Comment by ericnicolaas** [comment]
Hi @mgab71, 

Definitely working hard towards getting this released by May 25. Some of the GDPR changes are also dependent on updates in WordPress, which are expected in WordPress version 4.9.6, which is hopefully going to be released around the middle of the month. I'm aiming for Charitable 1.5 to come out pretty soon after that with our GDPR changes ready and available.

**Comment by ericnicolaas** [comment]
@mgab71: I should clarify that at this point, I'm planning to have a single opt-in that can be added, with the ability for the organization to customize the opt-in text. This gives you some flexibility in terms of having the donor agree to a certain way of being contacted:

> Yes, I am happy to hear from you via email. 

Or if you want to follow up via email or phone, just change the opt-in text:

> Yes, I am happy to hear from you via email or phone.

**Comment by ericnicolaas** [comment]
I am testing out this simple approach with a single checkbox that allows donors to opt-in:

<img width="449" alt="screenshot 2018-05-02 13 09 41" src="https://user-images.githubusercontent.com/676582/39504366-4105f4fa-4e0a-11e8-9ab9-10929b4a6777.png">

When a user is logged in, the opt-in is hidden along with the other user fields:

<img width="546" alt="screenshot 2018-05-02 13 15 06" src="https://user-images.githubusercontent.com/676582/39504451-e3abed7c-4e0a-11e8-8c96-7d35522fdd60.png">

When they expand their user fields, the opt-in appears with whatever they have previously selected:

<img width="537" alt="screenshot 2018-05-02 13 14 40" src="https://user-images.githubusercontent.com/676582/39504457-f00910a4-4e0a-11e8-985d-ba7e33c50a43.png">

I am suggesting that this field be an optional field, which can be enabled via the Customizer. The text for the opt-in can also be customized.

**Comment by ericnicolaas** [comment]
@wesfranklin Can I get your thoughts on the appearance & experience of this?

**Comment by wesfranklin** [comment]
@ericnicolaas Ah ok, that makes sense. So no border when logged out, and only a border when logged in and you have clicked 'update details'.

**Comment by ericnicolaas** [comment]
Yeah. I was just thinking about another alternative though, which is to group this field into the Terms and Conditions area:

![screenshot 2018-05-02 15 54 44](https://user-images.githubusercontent.com/676582/39508304-260d8d86-4e21-11e8-8e9f-f4c45bc5cbb7.png)

The section header "Terms and Conditions" might need to be tweaked to make a little more sense (maybe just "Terms"?) but this would avoid the issue you mentioned. It possibly also is a slightly more logical way to group the field, since it comes at the time when they are agreeing to the privacy statement & terms and conditions.

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah I think that's better.
