### ISSUE TITLE
Warnings in modal donation form

### ISSUE THREAD

**Issue by ElStupid** [Charitable/Charitable#43]
When I want to make a donation and click the button, in the modal I get two warnings.
Just after my details, and my user form gets filled fine.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'charitable_template_donation_form_donor_details' not found or invalid function name in D:\inetpub\ftproot\Localuser\FTP_crowdfunding\wp-includes\plugin.php on line 503

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'charitable_template_donation_form_donor_fields_hidden_wrapper_start' not found or invalid function name in D:\inetpub\ftproot\Localuser\FTP_crowdfunding\wp-includes\plugin.php on line 503

**Comment by ericnicolaas** [comment]
@ElStupid Could you try this with a different theme + with other plugins deactivated? And just to make sure that nothing went wrong with the upload process, could you try downloading the latest version from https://wordpress.org/plugins/charitable/ and testing against that?

**Comment by ElStupid** [comment]
I'm currently using it with Zerif Lite. Switching to Twenty Fifteen doens't solve the problem. Also disabling all other plugins doesn't solve it.
I'm going to try to fix it today

**Comment by ericnicolaas** [comment]
There is a new version of Charitable on WordPress. Could you try updating
to that?
On Mon, 30 Nov 2015 at 5:29 PM, ElStupid <notifications@github.com> wrote:

> I'm currently using it with Zerif Lite. Switching to Twenty Fifteen
> doens't solve the problem. Also disabling all other plugins doesn't solve
> it.
> I'm going to try to fix it today
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Charitable/Charitable/issues/43#issuecomment-160549385>
> .
>
-- 


*Eric Daams*Co-creator of Charitable

wpcharitable.com
twitter.com/wpcharitable

The fundraising alternative for non-profits.
Powered by WordPress.

**Comment by ElStupid** [comment]
Already did that, sorry for not mentioning.

**Comment by ElStupid** [comment]
Lost the warning by disabling WP_DEBUG in config.

**Comment by ericnicolaas** [comment]
Yes that would remove the error message, though it would not fix the underlying problem. Could you get in touch via [support](https://www.wpcharitable.com/support/) so we can work through why this is happening?

**Comment by rosanera** [comment]
I've the same problem, any news about this issue?

 call_user_func_array() [function.call-user-func-array]: First argument is expected to be a valid 
callback, 'charitable_template_donation_form_content' 
same for:
'charitable_template_donation_form_content' 
'charitable_template_campaign_content' 
'charitable_template_donation_processing_content'

**Comment by ericnicolaas** [comment]
@rosanera I have not been able to figure out why this would be happening. Are you saying you're on a version of PHP lower than 5.3? If so that _may_ have something to do with it, but can't say for certain. Would you mind getting in touch via (our support)[https://www.wpcharitable.com/support/] so we can follow up privately? 

Cheers, 
Eric

**Comment by ericnicolaas** [comment]
fe2532ba07639090341e6f54e876358e0606d1cf should fix this. The problem was that the hooks file was being loaded before the templates file, which resulted in the functions not existing at the time that the hooks were called.
