### ISSUE TITLE
Add 'Logout' Shortcode

### ISSUE THREAD

**Issue by wesfranklin** [Charitable/Charitable#431]
A lot of people have asked for a logout feature, because once they login there's no way to logout. A shortcode would be great because then they can put it wherever they want.

**Comment by ericnicolaas** [comment]
@wesfranklin Do you think it would also make sense to automatically include a logout button in the Profile form? And perhaps on the registration/login forms when you have already logged in?

**Comment by wesfranklin** [comment]
@ericnicolaas Yep.

**Comment by ericnicolaas** [comment]
I ended up not adding this to the profile form, but a logout link is added to the registration/login form when you are already logged in.

Shortcode also added:

```
[charitable_logout]
[charitable_logout redirect=https://mysite.com text="My special logout text"]
```

**Comment by ericnicolaas** [comment]
Docs done.
