### ISSUE TITLE
number_format expects parameter 2 to be a long, string given

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#438]
According to https://secure.php.net/manual/en/function.number-format.php `number_format` expects an `int` for the second param (`$decimals`), but it appears we are passing this as a string sometimes.

Interestingly enough, on 5.2 it doesn't generate a notice, but it does on 5.6+.

**Comment by ericnicolaas** [comment]
@dsoares Your fix looks good; Could you do a pull request to our `master` branch?

**Comment by dsoares** [comment]
I mistakenly did a PR on my own fork. Now it is on your `master` branch.

**Comment by ericnicolaas** [comment]
Thanks for the PR! Appreciate the contribution @dsoares
