### ISSUE TITLE
Bug with a comma in donation amount. 

### ISSUE THREAD

**Issue by memerson75** [Charitable/Charitable#439]
If I enter $1,000.00 for a donation, it changes the donation to $1.00. If I enter $1000.00 it saves correctly as $1000.00. This could trip someone up, and would be an easy fix! Alternatively, you could specify the format required in text under the field.

**Comment by ericnicolaas** [comment]
@memerson75 Ooh, that's nasty. What are your currency settings, including the decimal/thousands separators? Could you share a link to your site?

**Comment by ericnicolaas** [comment]
Just looking at #440, which you closed (so I'll assume that's no longer an issue) — are you referring here to the admin donation form or the public donation form?

**Comment by memerson75** [comment]
Here's a screenshot of the currency settings. Eric, I have this up on a password-protected staging site. Feel free to email me for specifics if you'd like to poke around.
<img width="673" alt="currency settings" src="https://user-images.githubusercontent.com/32335937/31868014-17ce2466-b767-11e7-9e64-4be836ef487b.png">

**Comment by memerson75** [comment]
User error on #440 :)

**Comment by ericnicolaas** [comment]
@memerson75 Thanks. Just to confirm: Was it in the admin donation form? Or in the frontend form?

**Comment by memerson75** [comment]
It was the admin form.
