### ISSUE TITLE
Inconsistencies in shortcodes

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#454]
**Inconsistencies in the filters:**

Some shortcodes pass the template `$view_args` and the shortcode `$args`:
see [`class-charitable-my-donations-shortcode.php`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-my-donations-shortcode.php#L103)

Some just the `$args`
see [`class-charitable-donors-shortcode.php`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-donors-shortcode.php#L109) and [`class-charitable-campaigns-shortcode.php`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-campaigns-shortcode.php#L98)

Some pass no args:
see [`class-charitable-profile-shortcode.php`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-profile-shortcode.php#L59)

And some don't filter the shortcode output at all:
see [`class-charitable-donation-form-shortcode.php`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-donation-form-shortcode.php#L63)

**Inconsistencies in how the attributes are parsed against the defaults.** 

Sometimes using [`wp_parse_args()`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-donation-form-shortcode.php#L40) but usually [`shortcode_atts()`](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-campaigns-shortcode.php#L47)

**Comment by ericnicolaas** [comment]
@helgatheviking Is this closed now?

**Comment by helgatheviking** [comment]
Yes, I messed up the title, but this is closed by https://github.com/Charitable/Charitable/pull/456
