### ISSUE TITLE
Pass shortcode attributes as parameter for action hooks in shortcode templates

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#455]
**Endgoal:** Add shortcode parameters to hooks in shortcode templates. 

We talked about adding the recurring donations automatically to the `[charitable-my-donations]` via the `charitable_my_donations_after` hook. But since there will also be a `[charitable-my-recurring-donations]` shortcode, some users may need/want to keep the recurring donations from displaying via `[charitable-my-donations]` (like with the `hide_login` parameter in the shortcodes that requiring logging in). 

So I wanted to add support for `[charitable-my-donations hide_recurring=1]` from Recurring, which is possible via the `shortcode_atts_charitable_my_donations` filter. 

However, there's currently no way to retrieve that `hide_recurring` attribute from the `charitable_my_donations_after` hook because it isn't passed to the shortcode output and then not passed from there to the output's various hooks. 

What do you think of passing the shortcode `$args|$atts` as part of the `$view_args` to each template so that in the templates I could add the `$atts` to each `add_action` hook?

I was thinking something like this in the my donations shortcode class

```
$view_args = array(
	'donations' => $donations,
	'user'      => $user,
	'atts'		=> $args // shortcode attributes
);
charitable_template( 'shortcodes/my-donations.php', $view_args );
```

and then in the `shortcodes/my-donations.php` template either:
```
/**
 * @hook    charitable_my_donations_after
 * @param object[] $donations An array of donations as a simple object.
 * @param  array $view_args All args passed to template. 
 */
do_action( 'charitable_my_donations_after', $donations, $view_args );
```
Where the shortcode atts are included as a key in the `$view_args` array or parsing out the attributes and just passing them as their own array:

```
$atts = $view_args['atts']`;
/**
 * @hook    charitable_my_donations_after
 * @param object[] $donations An array of donations as a simple object.
 * @param  array $atts All shortcode attributes.
 */
do_action( 'charitable_my_donations_after', $donations, $atts );
```

**Comment by ericnicolaas** [comment]
@helgatheviking In general I'm happy with this idea. I'll test your PR this week and work on getting it into 1.5.4.

By the way, for your shortcode, I'd suggest using underscores instead of dashes — that's more consistent with all the other Charitable shortcodes.

**Comment by helgatheviking** [comment]
Good point. Thankfully, it's already that way in my code! Just the github issue is wrong. I have that about 90% of the way done locally and will get it pushed up soon.
