### ISSUE TITLE
Custom input is wider than widget

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#458]
On narrow sidebars the input is too wide/not fluid:
![widget](https://d1ax1i5f2y3x71.cloudfront.net/items/381W2g352q2G3h2f0g25/Image%202017-11-11%20at%207.16.18%20PM.png?X-CloudApp-Visitor-Id=6af8b828a3cdca5483637e85399012aa&v=241900e2)

**Comment by ericnicolaas** [comment]
@helgatheviking I haven't been able to reproduce this. Which theme is this with?

**Comment by helgatheviking** [comment]
It's Storefront.
