### ISSUE TITLE
Feature request: select default suggested donation

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#470]
it may be helpful to have a pre-selected donation amount so that option can be highlighted on the initial page load.

**Comment by ericnicolaas** [comment]
I'm not sure about the need to include this in the UI, but happy to add a filter to allow this to be done programmatically.

**Comment by helgatheviking** [comment]
That's all I need right now. I tried filtering the amount in the session, but then you bypass the options entirely and get the "Your donation amount: $25 [click to change]" or similar message.
