### ISSUE TITLE
Fatal error on [charitable_submit_campaign] after Charitable 1.5.4 update

### ISSUE THREAD

**Issue by yavisht** [Charitable/Charitable#471]
Please help!

![screen shot 2017-11-24 at 4 14 00 pm](https://user-images.githubusercontent.com/6112201/33196239-aaccdc5a-d132-11e7-9a33-89b383866212.png)

![screen shot 2017-11-24 at 4 14 39 pm](https://user-images.githubusercontent.com/6112201/33196247-b3497afa-d132-11e7-9b78-d9e47dd486d7.png)

**Comment by yavisht** [comment]
Quick fix: Rollback to 1.5.3 https://github.com/Charitable/Charitable/releases/tag/1.5.3

**Comment by ericnicolaas** [comment]
Thanks for the heads up on this one @yavisht. I'll get a fix out today — I see what I did wrong and having a 🤦‍♂️ moment!

**Comment by yavisht** [comment]
@ericnicolaas No worries! Happy to help and test this amazing plugin!
