### ISSUE TITLE
Add a "meta" section within the "Your Details" fieldset, but at the end of it

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#495]
The "Your Details" fieldset contains user fields (name, address, phone, etc.) but also meta added by extensions (anonymous donations, newsletter checkbox, etc.).

Our Donation Fields API allows you to easily slot a field into the former (the user fields), but not the latter. This is inflexible if you want to add a field right after the newsletter checkbox, for example. 

We should make it just as easy to add a field to that part of the "Your Details" section as the rest.

**Comment by ericnicolaas** [comment]
@wesfranklin: I have tidied this up. Screenshots below.

Besides the changes we talked about, I also reduced the top/bottom padding of each fieldset (the bordered area) to 1.5em instead of 2em. I also changed the padding on the side to 20px instead of 2em.

**Logged out user:**

![screenshot 2018-05-01 16 19 10](https://user-images.githubusercontent.com/676582/39464283-8d7d1890-4d5b-11e8-9e2d-a4e2b9527d52.png)

**Logged out user, without meta:**

![screenshot 2018-05-01 16 19 39](https://user-images.githubusercontent.com/676582/39464284-8dba1bdc-4d5b-11e8-9960-c8823aa5fae5.png)

**Logged in user, collapsed:**

![screenshot 2018-05-01 16 11 41](https://user-images.githubusercontent.com/676582/39464036-653cbb2a-4d5a-11e8-9225-ffff41dd1a4c.png)

**Logged in user, expanded:**

![screenshot 2018-05-01 16 18 36](https://user-images.githubusercontent.com/676582/39464282-8d4123d0-4d5b-11e8-9ee9-e77bb43f36ae.png)

**Logged in user, expanded without meta:**

![screenshot 2018-05-01 16 19 54](https://user-images.githubusercontent.com/676582/39464285-8df62aaa-4d5b-11e8-8745-748946a51085.png)

**Two sections:**

![screenshot 2018-05-01 16 16 06](https://user-images.githubusercontent.com/676582/39464388-198ff226-4d5c-11e8-9140-debb4281d995.png)

**Comment by wesfranklin** [comment]
@ericnicolaas I think it should have the border when collapsed too?

**Comment by ericnicolaas** [comment]
@wesfranklin This?

![screenshot 2018-05-02 10 55 35](https://user-images.githubusercontent.com/676582/39500974-6871b64a-4df7-11e8-8c53-cd338bff598b.png)

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah.
