### ISSUE TITLE
Problem with charitable and redux theme options

### ISSUE THREAD

**Issue by ismailcseku** [Charitable/Charitable#499]
Hi,

I see a problem with charitable and redux theme options. The following code of "charitable-admin-menu.min.css":
<pre>
[class*=" icon-"], [class^=icon-] {
    speak: none;
    font-style: normal;
    font-weight: 400;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    font-size: 20px;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
</pre>affects redux icon styling.  See screenshot below:

![image](https://user-images.githubusercontent.com/1621384/34402178-42365664-ebca-11e7-9790-caa87ad474b5.png)

How can i overcome it?

Thanks
ismail

**Comment by helgatheviking** [comment]
@ericnicolaas I think you'll need to namespace the icons class.

**Comment by ericnicolaas** [comment]
Thanks @ismailcseku for reporting this. Thanks to @helgatheviking it should be resolved as of Charitable 1.5.9. :)
