### ISSUE TITLE
Use accounting.js to format the custom donation

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#50]
I use [accounting.js](http://openexchangerates.github.io/accounting.js/) in WooCommerce Name Your Price to format the user-entered value on the front-end. I think it could be useful here too. The money format settings are already in the admin, so it should be pretty straight-forward.

**Comment by ericnicolaas** [comment]
Sounds like a great idea! Are you interested in tackling it? 

Cheers, 
Eric

**Comment by helgatheviking** [comment]
Hi Eric,

I just finished writing it. I'm just having a bit of trouble with git. I'll send a PR as soon as possible.

cheers,
-kathy

**Comment by ericnicolaas** [comment]
:+1:
