### ISSUE TITLE
Cached list of pages in settings is not flushed when new pages are added

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#505]
The pages are cached like this:

```
wp_cache_set( 'filtered_static_pages', $pages, 'charitable' );
```

But we never delete this cache. When new pages are created or pages are deleted, we should delete this cache:

```
wp_cache_delete( 'filtered_static_pages', 'charitable' );
```

**Comment by ericnicolaas** [comment]
There is probably something to be set for ditching the cache here altogether since this really isn't such an expensive operation. We could cache it in the `Charitable_Settings` class as a property to avoid doing it repeatedly during a single request.

**Comment by cliftonc** [comment]
Thanks @ericnicolaas
