### ISSUE TITLE
charitable_template_from_session() does not support changing the template Class

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#509]
See https://github.com/Charitable/Charitable/blob/master/includes/public/charitable-template-helpers.php#L65

`charitable_template( $template_name, $args )`

needs to accept the 3rd template class in order to be usable by other extensions.

**Comment by helgatheviking** [comment]
I think I need this for Recurring 1.1.

**Comment by ericnicolaas** [comment]
Closed by 40b21a975528fde2a78eb45cff123f0b2d989ce7
