### ISSUE TITLE
Donation Receipt Endpoint has no checks for donation type

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#510]
When visiting the receipt endpoint: `http://site.com/donation-receipt/99/`

if 99 is not a simple donation of class `Charitable_Donation` then the following fatal error is triggered:

```
Catchable fatal error: Argument 1 passed to charitable_template_donation_receipt_summary() must be an instance of Charitable_Donation, instance of Charitable_Recurring_Donation given in wp-content\plugins\Charitable\includes\public\charitable-template-functions.php on line 702
```

**Comment by ericnicolaas** [comment]
@helgatheviking Can you refresh my memory about how receipts will work for recurring donations in 1.1? Will they use the same template as regular receipts, or something different? If the latter, then maybe we check for the donation type before loading the template.

**Comment by helgatheviking** [comment]
For recurring donations the link will be `http://jen.criticalink.dev/recurring-donation/88/` and it will have it's own template. 

In recurring, I am testing the donation type before displaying the content, [here](https://github.com/helgatheviking/charitable-recurring/blob/1ee7d3ddc164177d9857f781ed148121f3787b9b/includes/public/charitable-recurring-template-functions.php#L207-L209).

I believe you could do a similar type check [here](https://github.com/Charitable/Charitable/blob/972d563ea0ee291c29ea5a710dd4471efe6cdfd9/includes/public/charitable-template-functions.php#L670-L672)

Otherwise, you can visit a donation receipt endpoint with a recurring donation ID and you'll get fatal errors.
