### ISSUE TITLE
metabox select elements cut off bottom parts of letters

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#516]
Anything below the baseline gets lost. I think it is a combination of padding and height.

![image](https://user-images.githubusercontent.com/507025/35161844-0baa23c0-fd07-11e7-8b9d-248c9e1f3c7d.png)

**Comment by ericnicolaas** [comment]
@helgatheviking  I'm not seeing this in Opera or Firefox. Which browser are you seeing this in?

**Comment by helgatheviking** [comment]
I see it in Windows Firefox, Chrome, and Edge.
