### ISSUE TITLE
Loading gif is not transparent

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#518]
![image](https://user-images.githubusercontent.com/507025/35198325-c3f86b06-feb2-11e7-8eeb-de3148a5b0f8.png)

**Comment by ericnicolaas** [comment]
@wesfranklin Could you take a look at this? Current loading gif is at https://github.com/Charitable/Charitable/blob/master/assets/images/charitable-loading.gif

**Comment by wesfranklin** [comment]
@ericnicolaas That's weird!
Here's a new one, but it's bigger.
![charitable-loading-new](https://user-images.githubusercontent.com/13580400/35664151-4f90e626-0768-11e8-845f-bd9691b6d912.gif)

**Comment by wesfranklin** [comment]
@ericnicolaas Here's a resized version.
![charitable-loading-new](https://user-images.githubusercontent.com/13580400/35712332-0b0fd8b2-0809-11e8-9d22-a09c5e03854f.gif)
