### ISSUE TITLE
Link to confirm email address is not obvious

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#519]
It looks like you can still see your list of donations even if your email is not verified? And if you are logged in, why do you need to verify your email? 

![image](https://user-images.githubusercontent.com/507025/35288826-6150e724-002b-11e8-8073-3058dd33a870.png)

**Comment by ericnicolaas** [comment]
You can see any donations you made while logged in. The ones you can't see are the ones you made when you were not logged in; to see those, you have to confirm your email address. 

The thought behind this is to prevent people registering with an email address that is not their own and then seeing all the donations someone else has made.

**Comment by ericnicolaas** [comment]
I have changed the issue title to the display problem. I think in my testing the themes I used must have provided underlines for links.

I'm not sure how to solve this one. Couple options:

- Set a different colour for the links within notices. If so, what colour? It won't necessarily match the theme.
- Force an underline for links within notices.

@wesfranklin What do you think would be the best approach?

**Comment by helgatheviking** [comment]
>You can see any donations you made while logged in. The ones you can't see are the ones you made when you were not logged in; to see those, you have to confirm your email address.

What distinguishes between the two when getting donations? I got turned around here when building the similar page for recurring.

**Comment by wesfranklin** [comment]
@ericnicolaas I'd say force an underline.
