### ISSUE TITLE
Support manual donations without an email address

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#535]

**Comment by ericnicolaas** [comment]
With GDPR, erased donor data will have an invalid email address (`deleted@site.invalid` by default), so we need to start accounting for situations where a donation does not have a valid address. 

Given that, I think we can safely add support for manual donations lacking an email address, which is convenient for organizations receiving a lot of offline donations from people that they don't necessarily have an email address for.

**Comment by rafecolton** [comment]
Default should match pre-existing behavior for backwards compatibility.

**Comment by wesfranklin** [comment]
@ericnicolaas I'd say enabled by default - as long as there are no issues with backwards compatibility.

**Comment by helgatheviking** [comment]
maybe it could be a gateway setting?

**Comment by rafecolton** [comment]
Ok so it sounds like backwards compatibility is not an issue with user-facing donations.

Still thinking it might be a good idea to disable by default. It's much easier to omit data than to try to consolidate missing data. The use-case of omitting an email may work for some orgs, so enabling that feature should be possible, but the default behavior should be the one less likely to cause future problems—i.e. the one where all data is required.

**Comment by ericnicolaas** [comment]
I think I'll make this disabled by default, for the reasons outlined by @rafecolton. If we get a lot of requests from people wanting to be able to add donations without email addresses, we can put together a simple plugin for them. It only requires a single line of code to toggle this on.
