### ISSUE TITLE
Donation Filter and Export treat dates differently

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#546]
Hi @ericnicolaas,

Our accounting team found an interesting feature today: whey the filter donations by date, it shows donations made on the ending date in the range; however, when they export, it excludes donations made on the ending date.

I wouldn't call this a bug per se, but it is a bit confusing. I would expect the export to include donations made on the ending date, and I would also expect the two to behave the same way.

I'm currently running Charitable 1.5.8, so my apologies if this has already been fixed.

Best,
Rafe

**Comment by ericnicolaas** [comment]
Thanks for report @rafecolton! I just tested this out, and you're right; the export does not include the final day. 

I'll make sure we get this fixed in 1.6.

**Comment by rafecolton** [comment]
Awesome, thanks for fixing this so fast!
