### ISSUE TITLE
GDPR: Add informed consent notice to Licenses page 

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#547]
On the Licenses settings page, we should include a note explaining that providing a license key there will mean that we use it to check for license validity and allow automatic plugin updates. We can also explain that the license can be disconnected at any time.

**Comment by ericnicolaas** [comment]
@wesfranklin: Thoughts on this?

![screenshot 2018-05-11 06 30 29](https://user-images.githubusercontent.com/676582/39894037-ce74f42c-54e4-11e8-98be-9bdccbb246c6.png)

**Comment by ericnicolaas** [comment]
@wesfranklin Yeah I feel like it could be a little more prominent. Originally I had it above the buttons but it looks very plain there. Any ideas on a nice way to style it to be a little more noticeable and attractive?

**Comment by wesfranklin** [comment]
Would it work to style it like the payment gateway notice?
<img width="928" alt="screen shot 2018-05-15 at 3 26 16 pm" src="https://user-images.githubusercontent.com/13580400/40039162-667eca3c-5854-11e8-9502-2b7248e42111.png">
