### ISSUE TITLE
Notices from field registry on post.php screen for Recurring Donations 

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#553]
When I visit a recurring donation in the admin (`/wp-admin/post.php?post=88&action=edit`) I get the following warnings from the `release/1.6.0` branch:

>Warning: Illegal string offset 'section' in C:\Users\helga\Websites\jen.criticalink.test\wp-content\plugins\Charitable\includes\abstracts\abstract-class-charitable-field-registry.php on line 227

>Notice: Undefined index: a in C:\Users\helga\Websites\jen.criticalink.test\wp-content\plugins\Charitable\includes\abstracts\abstract-class-charitable-field.php on line 131

**Comment by ericnicolaas** [comment]
Could you test against `master`? Everything in `release/1.6.0` has been merged into `master`.

**Comment by helgatheviking** [comment]
Still seeing this with latest master

**Comment by ericnicolaas** [comment]
Closed by 8060f4a000ebaebef3caa2144f0ef350bde2bc31
