### ISSUE TITLE
GDPR: Store meta for erased records to indicate they were erased

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#555]
Erasing data is working nicely. However, it would be good to mark when a record such as a donation or donor is erased: this will help admin understand why a particular donation is missing all its data, for example.

**Comment by ericnicolaas** [comment]
Done this. I have added a notice to donations that have had their data erased. See screenshot:

![screenshot 2018-04-23 13 02 37](https://user-images.githubusercontent.com/676582/39105720-a01fb0fe-46f6-11e8-99ca-07030d825bdf.png)

@wesfranklin Any thoughts on the styling/appearance of this?

**Comment by wesfranklin** [comment]
@ericnicolaas Looks pretty clean, I think it's good.

**Comment by ericnicolaas** [comment]
Cool. Counting this as done then :)
