### ISSUE TITLE
GDPR: Add Privacy settings to control when data can be erased

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#556]
I have functional code ready that erases data, but it erases all personal data without taking into account whether that data may still be legally required to be retained.

In many (most?) countries, there is likely to be a requirement that data be retained for donations for at least a few years (varies by country), and this will trump the user's request to have their data erased. Therefore, I think we need to add a new setting that prevents data from being erased for donations made in the last X years.

We can also add a whitelist of fields that will be retained for donations made in this period. i.e. The organization may need to retain the donor's name and email address, but not their address. My gut is to make this an empty whitelist though; by default, all data is retained in the last X years.

**Comment by ericnicolaas** [comment]
@wesfranklin: Thoughts on the phrasing of this? Is it clear to you what these options mean?

**Setting**
![screenshot 2018-04-24 14 27 37](https://user-images.githubusercontent.com/676582/39166975-ae45d7e6-47cb-11e8-9099-b903d6c5c08b.png)

**Options**
![screenshot 2018-04-24 14 27 45](https://user-images.githubusercontent.com/676582/39166977-afdb3c7c-47cb-11e8-8acb-0455257a4190.png)

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah that makes sense to me

**Comment by ericnicolaas** [comment]
@wesfranklin Expanded on this a bit:

![screenshot 2018-04-24 15 53 52](https://user-images.githubusercontent.com/676582/39169624-b3af13f8-47d7-11e8-8071-20d979ffd991.png)

This now allows people to only keep certain pieces of data when someone requests to have their data erased. Legally, they have to be able to justify why they need to keep every piece of data they store.

This only affects personal data held for donations. Any personal data held about registered users not relating to donations is removed completely.
