### ISSUE TITLE
GDPR: Add "Terms and Conditions" field to donation form

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#558]
With the GDPR changes, we should add an option for people to include a "Terms and Conditions" checkbox in their donation form. Donations would not go through unless the terms and conditions have been agreed to.

**Comment by ericnicolaas** [comment]
@wesfranklin This is how WooCommerce are approaching it:

![screenshot 2018-04-27 11 12 13](https://user-images.githubusercontent.com/676582/39340245-2d652c06-4a0c-11e8-9365-b638b08f7cdf.png)

This is in their Settings area. 

In the Customizer, you can also set some of this:

![screenshot 2018-04-27 11 23 17](https://user-images.githubusercontent.com/676582/39340453-6d1408a8-4a0d-11e8-9a12-d166337da815.png)

When you click on "terms and conditions" in the checkout, the content of the page is loaded inline:

![screenshot 2018-04-27 11 35 25](https://user-images.githubusercontent.com/676582/39340779-2b6b260a-4a0f-11e8-9dbd-03a4403afcc2.png)

I think this all works fairly nicely. We may be able to leave out the Settings area stuff for now and just have this controlled via the Customizer.

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah that's really nice, especially the use of shortcodes.
