### ISSUE TITLE
Docs: Explain what personal data is stored by Charitable, and what is erased

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#561]

**Comment by ericnicolaas** [comment]
@wesfranklin See https://github.com/Charitable/Charitable/blob/master/PRIVACY.md. What do you think about having some docs like this here in the Github repo? 

Another option is to put it in the Github wiki, which we're not using at all at the moment: https://github.com/Charitable/Charitable/wiki

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah that could work. Do other people do that rather than having on their site?

**Comment by ericnicolaas** [comment]
WooCommerce use the wiki as a developer docs area: https://github.com/woocommerce/woocommerce/wiki
