### ISSUE TITLE
Missing campaign options tabs

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#566]
Latest master produces this when I am editing a campaign:
![image](https://user-images.githubusercontent.com/507025/39410918-4c836d22-4bc5-11e8-883c-908f26860e7e.png)

**Comment by ericnicolaas** [comment]
This is working ok for me. Here's what I'm seeing with `master` of both Charitable & Recurring:

![screenshot 2018-04-30 15 33 23](https://user-images.githubusercontent.com/676582/39416419-e7f7ee42-4c8b-11e8-8f30-cc1692d2994d.png)

**Comment by helgatheviking** [comment]
I think this is related to #553. I'm having trouble tracking it down, but it seems like the fields aren't being registered for me and so the fields are null. Is there anything you could have locally that isn't in the repo? I just deleted the whole folder and re-pulled from git to no avail.

**Comment by helgatheviking** [comment]
Best I can tell, it's related to [$field->$setting['section']](https://github.com/Charitable/Charitable/blob/1527b343769e3792ec57800bb2ef93edfb2916fc/includes/abstracts/abstract-class-charitable-field-registry.php#L227) not being an array

**Comment by ericnicolaas** [comment]
Closed by 8060f4a000ebaebef3caa2144f0ef350bde2bc31

**Comment by helgatheviking** [comment]
That solves it! Nice work, Eric!
