### ISSUE TITLE
Donation Actions: Resend emails should be tailored to donation type

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#575]
While trying to implement https://github.com/helgatheviking/charitable-recurring/issues/130 I noticed that the ability to resend actions is limited by this filter: `charitable_resendable_donation_emails`. And the donation ID/or object isn't passed to that filter so there's no way to distinguish between a donation that is just a plain one-time donation and a donation that is part of a recurring donation (either the first, or a renewal). This means that for example: resending the renewal donation receipt doesn't include the recurring donation/subscription info and is the same as a regular one-time donation even though we currently have two distinct emails for this.

**Comment by ericnicolaas** [comment]
Would a filter on the `can_be_resent()` method of the donation emails be enough? At that point, the object ID (i.e. donation ID) is known and returning `false` will prevent that action from appearing.

**Comment by helgatheviking** [comment]
That sounds like it would work...
