### ISSUE TITLE
Add wizard setup process

### ISSUE THREAD

**Issue by TinyGiantStudios** [Charitable/Charitable#582]
Charitable needs a few shortcodes to be added to select pages before it works optimally. It would be pretty cool to have those pages generated upon first activation AND populated with the relevant shortcodes.

Bonus points if those pages are also automatically assigned to the Charitable settings :)

**Comment by helgatheviking** [comment]
Agreed! Pretty sure it's in the plans: https://github.com/Charitable/Charitable/issues/144

**Comment by ericnicolaas** [comment]
Yep, I'd hoped to get this sorted with #144 in 1.6, but it's been pushed back to 1.7 for now. My ideal scenario is that all you'd need is a single page set up initially, and that can be done during the wizard.
