### ISSUE TITLE
Show whether contact consent was given in donation details

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#589]

**Comment by ericnicolaas** [comment]
@wesfranklin: I have integrated this into the donation details. See screenshots below. 

Note that "consent not asked" means the contact consent checkbox was not included in the donation form. This will be the case for all donations made prior to 1.6 since the field didn't exist then.

## Consent given
<img width="686" alt="screenshot 2018-05-29 07 10 02" src="https://user-images.githubusercontent.com/676582/40630163-6541a1a6-630f-11e8-8bb4-9c6ac9e4381f.png">

## Consent not given
<img width="678" alt="screenshot 2018-05-29 07 10 19" src="https://user-images.githubusercontent.com/676582/40630176-780e7c3c-630f-11e8-859a-5a61da237a5c.png">

## Consent not asked
<img width="678" alt="screenshot 2018-05-29 07 10 32" src="https://user-images.githubusercontent.com/676582/40630175-76490e1c-630f-11e8-8af2-408d5544246e.png">

**Comment by wesfranklin** [comment]
@ericnicolaas Looks pretty good. So what can Admin do with this? Is there a way we can make this useful with the Newsletter Connect extension?

**Comment by ericnicolaas** [comment]
@wesfranklin On its own it's not super useful. More just some information people can see at a glance.

One thing this still needs to cover is the possibility of a donor who has given their consented and then later withdrawn it; in that case, I feel like the donation details should reflect that.

The next way I'm planning to tie in the consent is through the Donations export: https://github.com/Charitable/Charitable/issues/590. That will allow admin to download a list of donors who are happy to be marketed to.

In terms of Newsletter Connect, my plan is for this checkbox to displace the one currently included in Newsletter Connect. Anyone who consents to being contacted can then automatically be added to an email marketing list.

**Comment by ericnicolaas** [comment]
@wesfranklin On the note of donors who originally agreed to be contacted but then withdrew their consent, what do you think about just phrasing it like this?

<img width="235" alt="screenshot 2018-05-29 10 27 11" src="https://user-images.githubusercontent.com/676582/40632904-eea404dc-632a-11e8-8790-3b9278d1b3f5.png">

It doesn't give a whole lot of details about what "Withdrawn" means, but it draws a distinction between someone who gave consent and withdrew it, and someone who never gave their consent in the first place.

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah I think that wording makes sense.
