### ISSUE TITLE
Add User Privacy and Terms & Conditions sections to Customizer

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#592]
As of 1.6, we have lumped all user privacy and terms & conditions fields in the Donation Form section, but these fields can apply elsewhere too. i.e:

- Privacy policy & contact consent can be included in the profile form and registration form as well.
- Terms & conditions can be included in the registration form as well.

With Ambassadors installed, all three of these could also be used in the campaign form.

Considering all that, I am proposing we add new sections to the Customizer for these fields. These settings will then affect all relevant forms.

**Comment by ericnicolaas** [comment]
Both sections added. Just need to fine-tune wording. @wesfranklin: Your thoughts on the wording below?

## Terms and Conditions

<img width="304" alt="screenshot 2018-05-30 11 20 22" src="https://user-images.githubusercontent.com/676582/40695530-c0995638-6400-11e8-9532-3dafc1709802.png">

## User Privacy

<img width="299" alt="screenshot 2018-05-30 12 05 41" src="https://user-images.githubusercontent.com/676582/40695767-ccc731f4-6401-11e8-8df3-aa2398482cd7.png">

<img width="288" alt="screenshot 2018-05-30 12 05 23" src="https://user-images.githubusercontent.com/676582/40695769-cf2cc8fa-6401-11e8-9270-7f4caaa67dba.png">

**Comment by wesfranklin** [comment]
Sounds fine to me.
