### ISSUE TITLE
Add Donors admin page

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#597]
We should include a Donors page in the dashboard to list all donors. This should include:

- Donor ID
- Email
- Name
- Number of donations (with link to filtered view of donations)
- Lifetime value
- Date joined
- Contact consent

**Comment by helgatheviking** [comment]
yes! I think I tried to do this once but didn't get anywhere.

**Comment by raftaar1191** [comment]
@ericnicolaas @helgatheviking 

I will love to do this. Is someone is working on this?

**Comment by helgatheviking** [comment]
I'm not! Send a PR! I think this would be very cool

**Comment by raftaar1191** [comment]
Sure @helgatheviking sending it

**Comment by ericnicolaas** [comment]
Closed by aa2f13e429fec0f7639177df3306432d7da1e21e
