### ISSUE TITLE
Add terms and conditions, privacy policy and contact consent to Registration Form

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#599]

**Comment by ericnicolaas** [comment]
@wesfranklin I have added these all into the registration form. What do you think of this?

![screenshot 2018-06-09 12 17 13](https://user-images.githubusercontent.com/676582/41186937-1069aa6a-6bdf-11e8-8722-81eb7d4b9c17.png)

**Comment by wesfranklin** [comment]
@ericnicolaas The spacing between lines seems a bit inconsistent?
