### ISSUE TITLE
Add support for querying by donation_plan to Charitable_Donations_Query

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#608]
Currently, no way (afaik) to get the all the donations of a particular `donation_plan` (ie. related to a particular recurring donation). 

Also, I think that would be faster if #520 was implemented as it wouldn't require a `JOIN` with the `post_meta` table.

**Comment by ericnicolaas** [comment]
@helgatheviking Can we use `post_parent`? That's the equivalent of getting the `donation_plan`, and doesn't require a join to `post_meta`.

**Comment by helgatheviking** [comment]
@ericnicolaas Yes we could, but there's no support for it yet in Charitable. Should support for that be added to Charitable or should I add it by filtering `charitable_query_where`?

**Comment by ericnicolaas** [comment]
@helgatheviking It looks like you've added your own query class extending `Charitable_Donations_Query`. Do you think it would still be worth implementing something like this into core, or should we close this issue?
