### ISSUE TITLE
Charitable_Form::render_field is deprecated Error

### ISSUE THREAD

**Issue by lesles08** [Charitable/Charitable#613]
I thought this error was solved (from other closed ticket):
Charitable_Form::render_field is deprecated since version 1.5.0 of Charitable! Use Charitable_Public_Form_View::render_field() instead. in /wp-content/plugins/charitable/includes/deprecated/class-charitable-deprecated.php on line 123
on: https://honor.gift/honor.gift/artthisweek/campaigns/help-poor-peoples-in-india/donate/

Am I doing something wrong?
Why am I still seeing this error? I am up to date on the plugin....

L

**Comment by ericnicolaas** [comment]
Hi @lesles08, thanks for reporting this! It looks like the Charitus theme is using an older way of displaying the form fields, one which is now deprecated. I have reached out to their developer to ask them to fix it, so hopefully you'll see an update to your Charitus theme soon that resolves this.

**Comment by lesles08** [comment]
Thank you for contacting them! I'm sorry I contacted you about it. After I
submitted this, I realized it had to be the theme...duh. Thank you again!

~ Leslie

**Comment by wpbean** [comment]
Hi @lesles08,

We released a new version of Charitus theme on ThemeForest.
Please update the theme on your site, The issue will be fixed.

Thanks 
Imran
XooThemes

**Comment by lesles08** [comment]
Hi Imran,

I just purchased this theme off a site called xxothemes.com a few days ago
but when I log in to xoothemes, I am not seeing an update nor do I see one
in the WP admin. All I see is the download link called "full package" in my
xoothemes account. Can you tell me how I get the update? Do I need to
download the "full package" again? Is it the updated version?

Leslie

**Comment by wpbean** [comment]
Hi @lesles08,

Ok. I just release the theme on our site as well. 

https://xoothemes.com/

Please log in to our site to download the latest version. Yes, download the full package now.

You can contact us in our support forum as well - 

https://xoothemes.freshdesk.com/

Thanks

**Comment by ericnicolaas** [comment]
Thanks @wpbean for fixing this up so quickly!

**Comment by wpbean** [comment]
@ericnicolaas, Thank you too for letting us know.

@lesles08, Good to know it works.
