### ISSUE TITLE
Add percent display option to stat shortcode

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#621]
User feedback:

> I am trying to get the [charitable_stat] shortcode to output the % donated as a number versus the progress bar. For example if it is 50% towards the goal, I would like to be able to display the number "50%" versus showing a progress bar that is 50% full.

Currently, the `[charitable_stat]` shortcode ([docs](https://www.wpcharitable.com/documentation/stats-shortcode/)) allows you to get the total raised by a campaign:

```
[charitable_stat display="total" campaigns=123] // $125.32
```

You can also show a progress bar: 

```
[charitable_stat display="progress" campaigns=123 goal=500] // Shows progress bar with 24.6% filled 
```

The user objective here is to be able to simply show the percentage raised, which is not currently possible. We could achieve this by adding a new "percentage" option for the display argument:

```
[charitable_stat display="percentage" campaigns=123 goal=500] // 24.6%
```

**Relevant code:**

- [Stat shortcode class](https://github.com/Charitable/Charitable/blob/master/includes/shortcodes/class-charitable-stat-shortcode.php)

**Comment by SirLoddington** [comment]
closed with b4fc1b7
