### ISSUE TITLE
Is there a Campaign total shortcode?

### ISSUE THREAD

**Issue by spresinal** [Charitable/Charitable#625]

**Comment by spresinal** [comment]
I only want to show the the running total in one area of my campaign page, is there a shortcode?
With the ability to change font size.
Thanks

**Comment by ericnicolaas** [comment]
@spresinal The Stats shortcode is what you want: https://www.wpcharitable.com/documentation/stats-shortcode/

You can change the font size with css.

**Comment by spresinal** [comment]
what about I only want to show our current campaign? I have been trying an array of codes and I can't get it to display only the current one.
[charitable_stat_campaigns id=1549]
