### ISSUE TITLE
Confusing UX when disabling "User: Email Verification" email

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#626]
Although selecting the "No" radio button and clicking "Save Changes" appears to work, when the page reloads, the "Yes" radio button is selected. It makes it seem like the setting was not changed.

Related to https://github.com/Charitable/Charitable/issues/482

**Comment by ericnicolaas** [comment]
Thanks for reporting this @rafecolton. I have been able to reproduce the issue; it specifically happens with radio input fields where the default value is 0. Fix will be out in Charitable 1.7.

**Comment by rafecolton** [comment]
Thanks for the quick fix! I see that you were checking for `empty()`, makes total sense.
