### ISSUE TITLE
Queries: Support Charitable_Donations_Query returning IDs

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#633]
Could use an `'output'     => 'IDs'` parameter. Currently you can get posts, donation objects, or a count. Can't yet tell if I'm going to need this to get Recurring Donations by a certain campaign, but I remember bumping into it a few times so logging it here.

I also think there the `query()` method should be renamed `get_query()` since it is a getter method.

**Comment by ericnicolaas** [comment]
Hmm, that's a good point. The workaround for now is you could do `'output' => 'posts'` and then run `wp_list_pluck( $records, 'ID' )` on the results. But obviously you're getting a less efficient SQL query.

**Comment by helgatheviking** [comment]
First stab at this in https://github.com/Charitable/Charitable/pull/634/commits/e0c2d777d2bb769ad0959c9bbd15eca332547f83 though I'm seeing I maybe don't need a `select_id()` method, just need to disable the donation/donor fields during `setup_fields()`.

**Comment by ericnicolaas** [comment]
Yeah, we don't need `select_id()`. Can instead just skip the extra fields in https://github.com/Charitable/Charitable/blob/master/includes/queries/class-charitable-donations-query.php#L112-L113

**Comment by helgatheviking** [comment]
Exactly. I think I did that locally. Will try to push that up tomorrow.
