### ISSUE TITLE
Pass $base_template_path parameter to locate_template(), etc

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#65]
Charitable needs a way for extensions to use the same theme override template process without having to re-write all your logic. If I want to load a template from my extension I have to duplicate all the charitable code. 

Instead, I propose that I be able to pass my extension's folder as the `$base_template_path` to all the Charitable core functions that look for a template. In the case where no value is passed, simply revert to your existing `get_base_template_path()` method.

**Comment by helgatheviking** [comment]
Closing because I have discovered that the same thing can be achieved by extending the `Charitable_Template` class and overriding the `get_base_template_path()` method.

**Comment by ericnicolaas** [comment]
@helgatheviking See https://github.com/Charitable/Charitable-Extension-Boilerplate/blob/master/src/includes/class-charitable-extension-boilerplate-template.php for the basic code I use in all extensions.

**Comment by helgatheviking** [comment]
Thanks @ericnicolaas. I am using the boilerplate, it just took me a while to get my head wrapped around how you are doing some stuff, but i got there eventually.
