### ISSUE TITLE
Upgrader stuck logging a step on every load

### ISSUE THREAD

**Issue by Rarst** [Charitable/Charitable#665]
Hi! I have a fresh development install of the plugin (git master checkout) and I have noticed that on every single page load it makes a database write to update upgrade log.

The trace is:

```
do_action('init')
wp-includes/plugin.php:465

Charitable_Upgrade->do_immediate_upgrades()
wp-content/plugins/charitable/includes/upgrades/class-charitable-upgrade.php:344

Charitable_Upgrade->walk_upgrade_actions()
wp-content/plugins/charitable/includes/upgrades/class-charitable-upgrade.php:389

Charitable_Upgrade->update_upgrade_log()
wp-content/plugins/charitable/includes/upgrades/class-charitable-upgrade.php:1011

update_option()
wp-includes/option.php:378
```

The upgrade step responsible seems to be `fix_empty_donor_ids` which checks for `Charitable_Upgrade->has_empty_donor_ids()` every run and logs it [around here](https://github.com/Charitable/Charitable/blob/master/includes/upgrades/class-charitable-upgrade.php#L384-L388).

I am guessing it's either missing a check that it doesn't _need_ to do this anymore or check is failing in some way.

**Comment by ericnicolaas** [comment]
Hey @Rarst, thanks for the catch on this! Looks like what's happening here is with upgrades that have an `active_callback` set, this callback function is checked before first checking whether the upgrade is done. As a result, Charitable checks whether the upgrade is done using the active callback, sees that it is, marks it as such by logging it in the db, then repeats the exact same process next time.

Switching the logic around so it first checks whether it's done according to the db log and _then_ checking the upgrade callback will fix this.

**Comment by Rarst** [comment]
Cheers! Seems that some debug output sneaked in there, I left a comment on commit. :)
