### ISSUE TITLE
PHP Warning array_key_exists warning

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#666]
`charitable_create_donation()` with no defined meta arg creates:

>Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/ubuntu/workspace/wp-content/plugins/charitable/includes/donations/class-charitable-donation-processor.php on line 602

I think it is because the `save_donation_meta()` does not store the merged `$meta` in the processor's `$donation_data`.... which may or may not be related to my issue with bulk generating data. 

Either `$this->get_donation_data_value( 'meta' );` needs a default `$this->get_donation_data_value( 'meta', array() );` or `save_donation_meta()` needs to set the `$donation_data['meta']` arg.

**Comment by ericnicolaas** [comment]
@helgatheviking I used your solution, but then swapped to using the fallback `array()` instead. Reason being that there are other places where we don't call `set_donation_data_value()` after updating a particular value (for example, after we get `donor_id`, we don't then update it in the `donation_data` array). 

So for now, to avoid any inconsistency, I'm going to keep `donation_data` the way it is, with just the `meta` data that is passed into the processor request originally.
