### ISSUE TITLE
Styles for admin metabox headings

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#670]
Only `h1` elements change the size, but they aren't semantically correct.

**Comment by ericnicolaas** [comment]
`h2` is also not semantically correct. `h3` does have a larger size & is bold. `h4` is usable (looks like it's the same size as regular text, but bold) and then the last two get progressively smaller. Since most usage should be restricted to `h3` and `h4`, I'm fairly happy with this as it is.
