### ISSUE TITLE
Display of My Donations shortcode for unconfirmed user

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#672]
Should the table headers display if not confirmed? Should I show "View My Recurring Donations" be an option?

![Empty My Donations table prompting user to confirm email address. Table headers still display.](https://user-images.githubusercontent.com/507025/55474801-1bc6e180-564d-11e9-950e-9437d6077cdc.png)

**Comment by ericnicolaas** [comment]
Hmm good point. The answer is probably no.
