### ISSUE TITLE
Donors Query: Add ability to get donors for multiple campaigns

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#691]
It would be nice if the following would work: `[charitable_donors campaign=49,110]`

But this requires that `Charitable_Donors_Query` supports a comma-separated list of campaigns.

**Comment by Rik44444** [comment]
Hi @ericnicolaas , is this a request to make it possible for a donor to support multiple campaigns with 1 donation? If so, hereby a 'thumbs up' , this would be a really big plus for our organization.

**Comment by ericnicolaas** [comment]
@Rik44444 No, that's not the purpose with this one. Instead, it's more for being able to get a list of donors that have donated to either campaign 49 or campaign 110, for example. Currently you can either get a list of donors who have donated to one specific campaign, or who have donated to _any_ campaign.

**Comment by ericnicolaas** [comment]
Closed by https://github.com/Charitable/Charitable/pull/850/
