### ISSUE TITLE
Donation Form: Add Customizer setting to remove login form

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#701]
The donation form has a login link at the top, providing an option for previously registered donors to log in before they make their donation:

![Screen Shot 2020-12-16 at 2 55 28 pm](https://user-images.githubusercontent.com/676582/102308722-d1b39a00-3fae-11eb-8428-af05697b12b5.png)

People often ask to remove this and it's possible with a bit of custom code:

https://github.com/Charitable/library/blob/master/donation-form/remove-login-form.php

It would be nice to add a way to remove this without code, via the Customizer. This can be added to the "Donation Form" panel in the Charitable Customizer area.

**Comment by helgatheviking** [comment]
Which login form do you mean?

**Comment by ericnicolaas** [comment]
Closed by https://github.com/Charitable/Charitable/pull/850/
