### ISSUE TITLE
Admin Donation Form: Add ability to edit donor details when selecting an existing donor

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#706]
This would be nice, but it could also be critical in some cases.

For example, if new required fields have been added to the donation form since the donor was initially created, it's likely that those fields have not been filled out for some donors. When you then select one of those donors to add a new donation for them, it fails silently, without telling you why. The reason is that the required fields aren't filled out, but those fields aren't shown at all, so there's no way to fix it. 

Creating a new user with the same email address also doesn't work, because Charitable prevents you creating a duplicate (makes sense).

**Comment by helgatheviking** [comment]
I'm thinking selecting an existing donor should auto-populate the fields with the donor info? Would need something more specific than the current `data-trigger-key="#donor-id" data-trigger-value="new" ` hide/show... maybe an ajax call.

**Comment by ericnicolaas** [comment]
Yes. It should show all the fields instead of hiding them as it currently does. The only thing I'd say though is that the email address should probably not be editable.
