### ISSUE TITLE
Custom labels on donation forms

### ISSUE THREAD

**Issue by gammaw** [Charitable/Charitable#718]
Do you consider making donation form labels customizable? For example, the "Your Donation" and "Enter donation amount" labels are static strings in the Charitable code base and can only be changed by directly editing the source code (which will be overwritten by any plugin update). Our specific issue is that we would like to show the currency on this form (the user may be unsure about the currency only looking at this form).

**Comment by ericnicolaas** [comment]
Hi @gammaw, 

There are a couple ways you can override this without changing the source code. 

You could use a translation plugin like TranslatePress or Loco Translate, or you can use a little bit of code. Here is a snippet of code you can adapt: 

https://github.com/Charitable/library/blob/master/general/change-plugin-text.php

See https://www.wpcharitable.com/documentation/3-ways-to-add-code-customizations-to-your-site/ for a guide to adding code like this to your site.

If you run into any problems with this, please get in touch via support@wpcharitable.com and I'll be happy to help!
