### ISSUE TITLE
Awkward alignment in Suggested Donations table

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#73]
The sortable donations change has left us with a little bit of an awkward alignment issue in the Suggested Donations table. Currently, this is what we have: 

<img width="561" alt="screen shot 2016-01-19 at 11 57 00 pm" src="https://cloud.githubusercontent.com/assets/676582/12419171/7a710e8e-bf08-11e5-8279-e63f0553804d.png">

Or for a campaign with suggested donations:

<img width="407" alt="screen shot 2016-01-19 at 11 58 32 pm" src="https://cloud.githubusercontent.com/assets/676582/12419194/92a6a072-bf08-11e5-8ae8-56a2838e51c7.png">

The main thing that bothers me is the alignment of the Amount cell. An alternative would be the following: 

<img width="559" alt="screen shot 2016-01-20 at 12 00 15 am" src="https://cloud.githubusercontent.com/assets/676582/12419225/cc0e2204-bf08-11e5-97ea-d20ff46fde3c.png">

Or with suggested donations:

<img width="405" alt="screen shot 2016-01-20 at 12 00 54 am" src="https://cloud.githubusercontent.com/assets/676582/12419245/e19de136-bf08-11e5-8ca0-0e6e72412255.png">

This feels better to me, though the "Amount" header no longer lines up with the amount input fields; but it all looks more natural to me. @wesfranklin, thoughts?

**Comment by ericnicolaas** [comment]
@helgatheviking Also pinging you on this for your feedback :)

**Comment by helgatheviking** [comment]
I have no strong feelings either way, so if you want to go ahead and make that "Amount" header span 2 columns, that's fine by me.

**Comment by helgatheviking** [comment]
I've gone ahead and changed it in Recurring Donations if that helps you decide.

**Comment by wesfranklin** [comment]
@ericnicolaas I'm not fussed either way. You could fix the problem by moving the grip handles to the right of the Description column.
