### ISSUE TITLE
My Account area 

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#75]
Just wondering if this was on a roadmap to have an area where you could see all your donations. That might be valuable on a site that supported multiple causes, ex: 

https://www.globalgiving.org
https://www.patreon.com/

**Comment by ericnicolaas** [comment]
Yep, it's been on the roadmap but keeps getting skipped (surprisingly, hardly anyone has requested it). Referenced in issue 41

**Comment by helgatheviking** [comment]
Guess it isn't that surprising the more that I think about it. It is needed if you're running a kickstarter clone, less necessary if you are just running a single campaign for your own nonprofit.

**Comment by rafecolton** [comment]
Adding a +1 for this feature - especially once there are recurring donations.  This will probably need to be done in conjunction with https://github.com/Charitable/Charitable/issues/82

**Comment by helgatheviking** [comment]
@rafecolton did you get my invite to [charitable recurring](https://github.com/helgatheviking/charitable-recurring/)? It's a hot mess right now, but coming along.

**Comment by rafecolton** [comment]
@helgatheviking yes I did, thank you!  I have some thoughts on the UI discussion, so I will leave comments shortly.  I have also committed to testing out the changes in the Authorize.net plugin.

**Comment by ericnicolaas** [comment]
Closing this. We closed #14 in 1.4.0 and the next phase of development towards this will take place in #144
