### ISSUE TITLE
`'show_in_export' => true` on custom donation fields doesn't seem to work

### ISSUE THREAD

**Issue by langy** [Charitable/Charitable#750]
Our client has asked that the custom fields we collect data for on their donation form could be included in their CSV exports.

After researching how to do this, I realised that this flag was already set to 'true' on those fields, but the field isn't being included in the export.

It is capturing the data fine, just not exporting it.

**Comment by ericnicolaas** [comment]
Hey @langy, 

I'm not aware of any issues with this, but happy to take a look to see what's going wrong. Could you post your full code for adding the fields here?

**Comment by langy** [comment]
Sure thing @ericnicolaas, thanks so much for your help.

`/**
 * Add a "Reason for Donating" field.
 */
add_action( 'init', function() {
	$field_donation_reason = new Charitable_Donation_Field(
		'donation_reason',
			[
				'label' => 'Reason for Donating',
				'data_type' => 'meta',
				'donation_form' => [
					'type' => 'textarea',
					'show_after' => 'country',
					'required' => false,
				],
				'admin_form' => true,
				'show_in_meta' => true,
				'show_in_export' => true,
				'email_tag' => [
					'description' => 'Reason for Donating',
				],
			]
	);

	/**
	 * Register the field.
	 */
	charitable()->donation_fields()->register_field( $field_donation_reason );
}, 100 );
`
Attached also a GIF of the (deidentified) CSV export, and a screenshot of one of the donations in the WP admin to show its data is definitely being submitted.

![CSV export]
(https://i.imgur.com/txYTTZ8.gif)

![WP admin meta field]
(https://i.imgur.com/tc5HVNt.png)

**Comment by ericnicolaas** [comment]
Hmm, you're right, that's not coming through at all. Will investigate.

**Comment by ericnicolaas** [comment]
@langy Just figured out the issue. In order to include the field in the export, you have to register it on `init` with a priority of less than `20`. The export happens on the `20` priority, so the field needs to exist before that for Charitable to know about it.

**Comment by langy** [comment]
@ericnicolaas Awesome, thanks so much for your time spent investigating and realising the solution!
