### ISSUE TITLE
Polylang: Automatically pick up the current language version of an endpoint

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#790]
If you're using Polylang and you are viewing the website in a language that is not the default, you would most likely want the `charitable_get_permalink()` result to return the variation of the page in your local language. 

For example, `charitable_get_permalink( 'profile' )` should return the Profile page in the language you're using, not the base language. 

This applies to a few different pages:

- [x] Profile
- [x] Login
- [x] Registration
- [x] Donation Receipt
- [x] Privacy Policy
- [x] Terms and Conditions

**Comment by Rik44444** [comment]
a note to other Charitable users: if you use TranslatePress instead of Polylang, this problem is solved.
