### ISSUE TITLE
minor translation error in Donations overview

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#792]
Our base country is set to the Netherlands. If I view our donations page in English, it looks like the image below. The status column is in Dutch, and not in English.

![afbeelding](https://user-images.githubusercontent.com/42555414/84589409-98974300-ae2e-11ea-81d2-07bd91b86339.png)

**Comment by ericnicolaas** [comment]
Hey @Rik44444 :)

I haven't been able to reproduce this issue. I set up an example site using Polylang at https://sandbox.wpcharitable.com/polylang/. After making a donation, these are the English & Dutch versions:

![Screenshot 2020-06-16 16 09 08](https://user-images.githubusercontent.com/676582/84740067-e3aa8500-afeb-11ea-9775-5fb9d875883d.png)

![Screenshot 2020-06-16 16 09 14](https://user-images.githubusercontent.com/676582/84740071-e4dbb200-afeb-11ea-8a87-64ee4a3e6f8c.png)

Are you still using Polylang, or is this with a different plugin? Can you double-check that you don't have the English translated to the Dutch for these phrases?

**Comment by Rik44444** [comment]
Hi Eric,
Ok then the problem probably lies with my installation. I'm using TranslatePress now, but am also still using Loco Translate for translation of the Reach Theme. I'll check if there's a problem there.

**Comment by Rik44444** [comment]
I was able to fix it in TranslatePress - I think i probably made a translation error, sorry for making you put in the time to duplicate!
