### ISSUE TITLE
Make it easier to add options to [charitable_email] shortcode

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#80]
Relates to https://github.com/Charitable/Charitable/pull/79

Since `campaign` and `donation` are protected attributes on `Charitable_Email` and its subclasses, it is not possible to access them in a callback, which is required for the `charitable_email_content_fields` hook.  

In order to add to the shortcode, it is necessary to subclass the email class in question, add a public function that accesses `campaign`, and use that inside of the function called from `$fields[ <shortcode_field> ][ 'callback' ]`.  

And I think this only worked in my case because the hook for `Charitable_Ambassadors_Email_New_Campaign` doesn't exist (see ambassadors issue 1).

It would be really handy to be able to access attributes of `campaign` and `donation` on `Charitable_Email` subclasses.

Below is an example of trying to add the `campaign_url` field.  Note the "FIXME" comment.

```php
function ch_add_campaign_url_field( $fields, $email ) {
  $fields[ 'campaign_url' ] = array(
    'description' => 'The permalink for the campaign',
    'callback' => 'ch_campaign_url_field',
  );
  return $fields;
}

function ch_add_campaign_url_field_preview( $fields, $email ) {
  $fields[ 'campaign_url' ] = 'http://www.example.com/campaigns/fake-campaign';
  return $fields;
}

function ch_campaign_url_field( $empty_string, $args, $email ) {
  return $email->get_campaign_url();  // FIXME: If this function doesn't exist, we have no way to get the campaign guid
}

add_filter( 'charitable_email_content_fields', 'ch_add_campaign_url_field', 10, 2 );
add_filter( 'charitable_email_preview_content_fields', 'ch_add_campaign_url_field_preview', 10, 2 );

```

**Comment by ericnicolaas** [comment]
In 1.3.0, I have added public getter methods to retrieve the `$campaign` and `$donation` objects. I also switched around the arguments that are passed to the `charitable_email_content_field_value_$field` hook, so the email object is available as the third argument.

**Comment by ericnicolaas** [comment]
455723f58e05dfdbc7a57adae42f55e3f66234d1

**Comment by rafecolton** [comment]
I saw the switch in arguments that now passes the email object, but I missed the getter methods for donation and campaign.  That's exactly what I needed - thanks!
