### ISSUE TITLE
when donor is not registered,after submit donation form,didn't pass to process_donation function 

### ISSUE THREAD

**Issue by mohseni676** [Charitable/Charitable#806]
Hi
I am developing an payment gateway for charitable, only required field set to phone number, and I won't donor registered and every body comes to donation form can pay only by enter his/her mobile number.
my problem is when donor is registered after press donation button every thing works perfectly and process_donation function is called, but when donor is not registered process_donation function is not called and display a page with message that "you will redirect to payment gateway"
please help me
thank you
in log says:
A donation "cannot" be inserted without valid user

**Comment by mohseni676** [comment]
in log says:
A donation "cannot" be inserted without valid user

**Comment by ericnicolaas** [comment]
Hi @mohseni676

You will get this error regarding a valid user if there is not sufficient data for Charitable to create a donor record. At a minimum, you must have an email address. So my recommendation is to make both the email and phone number required — that should fix the issue.
