### ISSUE TITLE
 Admin: New Campaign Notification E-Mail not working when Campaign published after saving it as draft

### ISSUE THREAD

**Issue by Buesi** [Charitable/Charitable#813]
Neither Admin nor Campaign creator get an email notification when new campaign is first saved as a draft and then published without editing (by clicking on the publish button next to the editing one).

I can provide more info if needed :) 
Cheers

**Comment by ericnicolaas** [comment]
Thanks for reporting this @Buesi! I'm going to close it here, but I have added it to the issue tracker for Ambassadors.

**Comment by Buesi** [comment]
Hi @ericnicolaas 

Thanks for your reply!

Cheers
Dorena
