### ISSUE TITLE
Feature request: making donating without email address possible

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#820]
We have some students working on our project now, and they discovered that more than half of all donors to charity in the Netherlands would prefer to donate without giving any personal information, even their email address. With Charitable, giving an email address is mandatory. This is a feature request to make it possible to donate without given your email address, so to be able to set user_email to not required in the various forms.

PS: i noticed each donor gets a unique ID nr in the DB, so perhaps this means that the email address can be made optional?

**Comment by ericnicolaas** [comment]
@Rik44444: Donations on the front-end are required to include an email address. In the admin, it's possible to add donations without an email address, though this requires a little bit of code:

https://github.com/Charitable/library/blob/master/admin-donation-form/allow-manual-donations-without-email.php
