### ISSUE TITLE
testing staging option

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#825]
a question relating to the use of staging environments in Softalicous app installer. We are making use of this option, it's really quite handy (staging.future.ngo is our staging environment, https://future.ngo our main site). However, with Mailpoet, a plugin we use, we've run into the issue that when pushing our staging environment to live, the people who have enlisted on the main site (which is where they will enlist, nobody knows of the staging site), are deleted because the list of subscribers is overwritten by the staging site.

Do you know how this goes with Charitable? Can we use the staging site option? Or will it delete new donors and donations from our database when we push the staging site to live? Perhaps good to test this and add it to your FAQ that this is either possible or not possible.

**Comment by Rik44444** [comment]
to add to this: it is possible to exclude specific DB tables when pushing a staging site to live. This would appear to be the solution for MailPoet: to exclude the Mailpoet tables when pushing to live. However, this may pose a problem for Charitable Re campaigns: because the campaigns are listed in the general WPPX_posts and _postsmeta tables. The donations and donors tables could be easily excluded. I have not tested this yet, but i think pushing to live should be possible that way without overwriting changes in the Charitable donors and donations tables on the main site.

**Comment by Rik44444** [comment]
I deciced to do some testing myself: hereby the confirmation that if you do a regular "push to live" from the staging site, after:
1) adding a mailpoet subscriber
2) adding a charitable donation + new donor
3) adding a charitable campaign
to the main site, so the "non-staging" site, that ALL are deleted once the staging site. 

Testing next if they are deleted when i exclude several tables

**Comment by Rik44444** [comment]
hereby results of testing when all tables in this screenshot are excluded from pushing to live: all points 1-3 remain intact on the live site, so new subscribers, donations and campaigns for Charitable and Mailpoet subscribers as well. 

Still need to test if website text changes ARE pushed to live, when these tables are excluded. This is needed, otherwise the staging has no purpose :)

**Comment by Rik44444** [comment]
@ericnicolaas I also suggested to Mailpoet: perhaps good to connect with Softalicious app installer, to see if the relevant tables for Charitable can be unchecked by default in pushing sites to live?

**Comment by Rik44444** [comment]
I will forego the last test (if relevant content is pushed to live when we make changes in the Dev environment), because we will not be able to use staging: https://github.com/Charitable/Charitable/issues/826

Still , might be good for Charitable to test if the staging environment works properly with Charitable and post that on your website?

**Comment by ericnicolaas** [comment]
@Rik44444 This was covered in my response to https://github.com/Charitable/Charitable/issues/826 but just to clarify for anyone who misses that thread, if you are using a staging environment and you are updating _content_ on the staging site, pushing content back to the live site will result in any interim changes to the live site's data being overwritten. This affects Charitable, MailPoet and just about any other plugin that records data in the database. 

The main way that we use staging sites is to pull a copy of the live site and check any code changes (i.e. not content changes). If you want to migrate changes to the content, such as with WPML translations, check if there is an export option available for exporting just that. 

Alternatively, for migrating content you can look at the WP All Import plugin and its twin, WP All Export.
