### ISSUE TITLE
PHP Error when using Charitable with Oxygen Builder and Twenty Twenty Theme

### ISSUE THREAD

**Issue by yanggao1898** [Charitable/Charitable#829]
There's a very peculiar bug that seems to trigger when Charitable is installed along with Oxygen Builder, while using Twenty Twenty as the active theme. Even though Oxygen Builder should completely bypass the Wordpress theme, when using Charitable, there's some function that triggers an error somehow in PHP, and causes a 500 error when viewing any WP page. In the debug.log, I get the following:

> [02-Oct-2020 07:06:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function twentytwenty_get_color_for_area() in E:\xampp\apps\wordpress\htdocs\wp-content\plugins\charitable\includes\compat\charitable-compat-functions.php:118
> Stack trace:
> #0 E:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(287): charitable_compat_theme_highlight_colour('#f89d35')
> #1 E:\xampp\apps\wordpress\htdocs\wp-includes\plugin.php(206): WP_Hook->apply_filters('#f89d35', Array)
> #2 E:\xampp\apps\wordpress\htdocs\wp-content\plugins\charitable\includes\admin\customizer\class-charitable-customizer.php(247): apply_filters('charitable_defa...', '#f89d35')
> #3 E:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(287): Charitable_Customizer->register_customizer_fields(Object(WP_Customize_Manager))
> #4 E:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #5 E:\xampp\apps\wordpress\htdocs\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
> #6 E:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-customize-manager in E:\xampp\apps\wordpress\htdocs\wp-content\plugins\charitable\includes\compat\charitable-compat-functions.php on line 118

This error goes away when a different theme is selected.

**Comment by ericnicolaas** [comment]
Thanks for reporting this @yanggao1898. Charitable provides a compatibility layer for Twenty Twenty, but looks like what's going wrong here is that the `twentytwenty_get_color_for_area()` function is getting called in the admin area, when it isn't available. I'll have a fix available in Charitable 1.6.45.
