### ISSUE TITLE
wrong translation payment confirmation screen

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#837]
See schreenshot below, there is a "+" that should not be there in the title. I tried correcting this in [Translate Wordpress](https://translate.wordpress.org/projects/wp-plugins/charitable/), but this sentence does not appear to exist there.

![image](https://user-images.githubusercontent.com/42555414/98521386-a92fd600-2273-11eb-8e5e-7987a9df7af1.png)

**Comment by ericnicolaas** [comment]
@Rik44444 That looks like the page title, not something that Charitable / Reach is generating.

**Comment by Rik44444** [comment]
hi @ericnicolaas , i looked at our Pages, but we did not make a page for this. I'm fairly sure it is an automatic page in Charitable / Reach. Are you sure?

**Comment by ericnicolaas** [comment]
@Rik44444 I still don't see where this is coming from. Charitable by default has the text in English, so it's being translated somewhere along the line and I suspect that's where the plus is coming from.

**Comment by ericnicolaas** [comment]
I also checked the official Dutch translation on WordPress and it has it as "Betalingsbewijs donatie" there. 

https://translate.wordpress.org/projects/wp-themes/reach/nl/default/?filters%5Bterm%5D=Donation+Receipt&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
