### ISSUE TITLE
page redirection after  payment failed

### ISSUE THREAD

**Issue by Krishna321-2** [Charitable/Charitable#839]
if payment is being failed in Instamojo (test mode)
[
![image](https://user-images.githubusercontent.com/71020943/98778683-b9cd8100-2418-11eb-9a97-62a18b80ca6a.png)
](url)
and if i select cancel option it redirect to this receipt page [https://www.asthawelfarefoundation.com/donation-receipt/2593/?donation_key=cc9515d24fa48eb70f0a7afea4861d8c&payment_id=MOJO0b11A05A50950197&payment_status=Failed&payment_request_id=0bd5678eab8947dd8a78562bb8218a0b](url) instead of payment failed receipt page by charitable plugin.
 [
![image](https://user-images.githubusercontent.com/71020943/98778952-20529f00-2419-11eb-98db-5299ccefae73.png)
](url)

note:-also in donation dashboard this donation is showing pending status.

**Comment by ericnicolaas** [comment]
Hi @Krishna321-2, 

Sorry for missing this. This looks like an issue with the Instamojo plugin. Could you reach out to the developer of that plugin?

Cheers, 
Eric
