### ISSUE TITLE
private versus protected methods/properties

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#84]
Hi Eric,

Today I started working on `Charitable_Recurring_Donation` class. I think it makes sense to extend the `Charitable_Donation`. They're pretty similar and it'd be good to keep some of the core methods. However, I'm running into some issues with the fact that so many methods and properties are set to `private`. This means I can't access them from a child class. What's the thinking there? Why is the `$donation_data` private? Why is `get_status()` private? 

If you're not ok with public properties, what about protected? That should still allow a child class to access them right?

**Comment by ericnicolaas** [comment]
@helgatheviking I'm happy changing the properties to `protected`, as well as any private methods. Mostly I just prefer to keep the properties `protected` or `private` so that they cannot be overwritten from outside the class.

**Comment by helgatheviking** [comment]
Sounds good. Everything to `protected` would be a good start. I'd say I would tack it on to #74, but I'm guessing I need to redo that one.

**Comment by helgatheviking** [comment]
While we're at it, I'd also like to make the case that the `Charitable_Donation` class should have very few, if any `static` functions that don't pertain directly to the `$donation` object should be in something like `charitable-donation-functions.php`.... which you already have.

**Comment by helgatheviking** [comment]
I think this was closed by 49443d3d73182463b4fca0bf1ffa3d2fc031f45e
