### ISSUE TITLE
Campaign set up as a fundraiser incorrectly showing as a campaign for the organization.  

### ISSUE THREAD

**Issue by daamsie** [Charitable/Charitable#840]
A campaign was found that had amounts applied to it from a child campaign. 

When looking into that child campaign, the settings window looked as follows

<img width="946" alt="Screen Shot 2020-11-16 at 12 08 05 pm" src="https://user-images.githubusercontent.com/740324/99204468-dfd49600-2809-11eb-8c7a-ae2844b1a207.png">

Adjusting the campaign to be a fundraiser for another campaign showed that there was a parent campaign selected. Resetting the parent to be itself resolved the issue. 

Unsure exactly what is causing it, but a hypothesis is that it was set up as a child campaign initially, then the Campaign Ambassadors settings were changed and that caused the issue. Unable to reproduce so far locally though. 

This needs more investigation.

**Comment by ericnicolaas** [comment]
This is an Ambassadors-specific issue, but I think this should be resolved now. I did discover issues where when you saved a campaign, it reset some values because of some disabled fields. That's fixed now, and I'm guessing this is probably related to that.
