### ISSUE TITLE
Profile fields on 'campaign submission page'

### ISSUE THREAD

**Issue by giancta92** [Charitable/Charitable#844]
Hi, I have a page with the shortcode [charitable_submit_campaign] for use by ambassadors. I wish I could disable the profile edit fields, how can I disable them?

**Comment by ericnicolaas** [comment]
@giancta92: You can do that with a bit of custom code. There's a code snippet here that you ca adapt if you want to remove a few specific fields: https://github.com/Charitable/library/blob/master/extensions/ambassadors/campaign-submission-form/remove-all-user-fields-except-for-basics.php

If you want to remove the entire section, you can use this:

https://github.com/Charitable/library/blob/master/extensions/ambassadors/campaign-submission-form/remove-user-fields.php

Note that if you do that, you'll need to make sure that user registration takes place _before_ the campaign is submitted. If you're having user registration take place after campaign submission, the form needs to collect an email address at the very least.

**Comment by giancta92** [comment]
Perfect!!!! thanks Eric, it worked for me, I had been removing each field individually, but I always had the avatar field and the header. You saved me the research hahaha
