### ISSUE TITLE
Displaying campaigns for multisite generates duplication of fields

### ISSUE THREAD

**Issue by giancta92** [Charitable/Charitable#846]
Hi, I have a multisite in development with the charitable plugin. I custom code the [charitable_my_campaigns] shortcode to display campaigns from all sites. It works well for me, except that from the 2nd site some fields start to duplicate [screenshot attached].

What could you be doing wrong?

This is my code:

`add_shortcode( 'charitable_network_my_campaigns', function() {
	// WP_Site_Query arguments
	$argus_campaigns = array(
		'site__not_in'	=> 1,
		'fields'		=> 'ids',
		'public' => 1,
	);

	// The Site Query
	$site_query_campaings = get_sites($argus_campaigns);

	ob_start();
	
	// The Loop
	if ( $site_query_campaings ) {
		foreach ( $site_query_campaings as $site_id ) {
			//print_r(get_blog_details($site_id))
			switch_to_blog( $site_id );
			//include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
			if(class_exists('Charitable')){ ?>
						<?php
						//echo 'Campañas en ' . get_bloginfo( 'name' );
						echo do_shortcode('[charitable_my_campaigns]');	
						?>

			<?php	
			}
			restore_current_blog();
		}
	}	
	
	return ob_get_clean();
} );`

![Screenshot_2020-12-15 Mis campañas – Manos que Suman(1)](https://user-images.githubusercontent.com/12267893/102304174-d171bb00-3f2a-11eb-8147-708e6f7b7990.png)
![Screenshot_2020-12-15 Mis campañas – Manos que Suman](https://user-images.githubusercontent.com/12267893/102304177-d3d41500-3f2a-11eb-9576-10ba586f735c.png)

**Comment by ericnicolaas** [comment]
@giancta92 I've been able to replicate this by simply having [charitable_my_donations] added to the same page multiple times. It's an issue in Ambassadors, so I have opened the issue in that repo and will close this one.
