### ISSUE TITLE
Outlining of bullets and numbered lists

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#852]
Outlining of bullets and numbered lists is strange when the default font is set to be outlined "centered". The bullets line out all the way to the left, while the text is in the center. Bullets/numbers should be just before the text, like in MS Word. 

![image](https://user-images.githubusercontent.com/42555414/102708268-058a0a80-42a2-11eb-8ac2-ed0900da0c87.png)

Office writer screenshot (how it should be):
![image](https://user-images.githubusercontent.com/42555414/102708296-38cc9980-42a2-11eb-9efa-a9d9d57611c6.png)

**Comment by Rik44444** [comment]
i just noticed this problem occurs only in Chrome, not in Firefox (below a screenshot of Firefox). Does not make it less relevant, since 90% of browsers now run on Chrome, but still, thought it good to mention

![image](https://user-images.githubusercontent.com/42555414/102708327-7b8e7180-42a2-11eb-8a70-acb5bc33477b.png)

**Comment by ericnicolaas** [comment]
@Rik44444 This is also a Reach issue. I think it's related to another one you reported previously. Added mention here: https://github.com/Charitable/Reach/issues/86
