### ISSUE TITLE
unneccessary sliders in our individual post

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#854]
there are unneccessary sliders in our individual posts, even in really short ones. They are absent in the posts Overview page. See below screen shots and the following links:

Overview page: ( https://toekomstfonds.nl/nieuws/ )

![image](https://user-images.githubusercontent.com/42555414/102721360-942a7600-42fa-11eb-9a04-54e28832bdcd.png)

Individual post pages with unneccessary sliders on the right: (https://toekomstfonds.nl/2020/12/20/toekomstfonds-belicht-op-impact030-website/  and   https://toekomstfonds.nl/2020/09/25/eerste-nieuwsbrief/ ) 

![image](https://user-images.githubusercontent.com/42555414/102721344-8674f080-42fa-11eb-950e-dd1fecd20037.png)

![image](https://user-images.githubusercontent.com/42555414/102721355-8e349500-42fa-11eb-823c-659f6279dd13.png)

**Comment by ericnicolaas** [comment]
Thanks @Rik44444. I've added this issue to the Reach repo as it's specifically a Reach problem, not related to Charitable itself. This is the open issue for it:

https://github.com/Charitable/Reach/issues/94
