### ISSUE TITLE
option to reverse anonymous donations 

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#855]
request to reverse the checkbox for anonymous donations: What we would like is that the default is that donations are anonymous, but that people can check a checkbox that says "I would like my name to be shown on the Future Fund website, together with the donation i have made to the charity"

**Comment by ericnicolaas** [comment]
@Rik44444 I'm closing this here as it's specific to the Anonymous Donations, but I have opened it there as a feature. It's a nice idea and we're working on it. :)
