### ISSUE TITLE
feature request: full payment platform, with all Charitable options

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#856]
Feature request for the ability to use a payment platform that:
1. offer a wide range of payment options, incl at least iDEAL, Paypal, Visa, Mastercard, Apple Pay, Google Pay
2. that is able to use all Charitable functions, particularly recurring donations (this one is really important to organizations dependent on donations for income)

As i've understood it, there are currently some payment platforms that do some of this for Charitable, but not one that does all of it. It is (very) important to us, so therefore the feature request here

**Comment by ericnicolaas** [comment]
@Rik44444 It seems like Mollie would be a good candidate for taking care of this. We have a plugin in development to support Mollie. It's still a little way away.
