### ISSUE TITLE
Weglot compatibility 3.3.0

### ISSUE THREAD

**Issue by remyberda** [Charitable/Charitable#861]
Hi there, I'm the developer of Weglot plugin.
In our latest version, the 3.3.0, we have changed the function `getForLanguage` that needs a language object, not a two letter code, so you need to change it in your plugin.

In file includes/compat/class-charitable-weglot-compat.php, change on line 134:
`return weglot_create_url_object( $default )->getForLanguage( weglot_get_current_language() );`
to
`return weglot_create_url_object( $default )->getForLanguage( weglot_get_service('Language_Service_Weglot' )->get_language_from_internal(weglot_get_original_language()) );`

And on line 158:
`return charitable_get_permalink( $endpoint, $args ) === weglot_create_url_object( weglot_get_current_full_url() )->getForLanguage( weglot_get_original_language() );`
to
`return charitable_get_permalink( $endpoint, $args ) === weglot_create_url_object( weglot_get_current_full_url() )->getForLanguage( weglot_get_service('Language_Service_Weglot' )->get_language_from_internal(weglot_get_original_language()) );`

**Comment by ericnicolaas** [comment]
@remyberda Thanks for letting us know. Will the change you gave be backwards compatible with Weglot pre-3.3.0?

**Comment by remyberda** [comment]
No it will not so you might want to check the Weglot version and only do this change if Version is above 3.3.0, don't hesitate if you need any more info :)
