### ISSUE TITLE
stats shortcode returns 0 on multisite 

### ISSUE THREAD

**Issue by giancta92** [Charitable/Charitable#901]
Hi, I have a multisite running Charitable. I'm trying to get the total amounts for each site within my network using 'switch_to_blog' and the statistics shortcode; but, it always returns 0 for all sites. 

My code is this: 

	$argus = array(
		'fields'		=> 'ids',
	);
	$qsitio = get_sites($argus);
	if ( $qsitio ) {
		foreach ( $qsitio as $qsiteid ) {
			switch_to_blog( $qsiteid );
			if(class_exists('Charitable'))  {
				echo do_shortcode('[charitable_stat display=total]') . '<br>';
			}
			restore_current_blog();
		}
	}

**Comment by ericnicolaas** [comment]
I'm closing this issue as it's more of a customization question. For what it's worth, I have tested the following code and found it to work as expected:

```
add_shortcode( 'charitable_network_stats', function() {
	// WP_Site_Query arguments
	$argus = array(
		'site__not_in'	=> 1,
		'fields'		=> 'ids',
	);

	// The Site Query
	$site_query = get_sites($argus);

	ob_start();
	
	// The Loop
	if ( $site_query ) {
		foreach ( $site_query as $site_id ) {
			//print_r(get_blog_details($site_id))
			switch_to_blog( $site_id );
			if ( in_array( 'charitable/charitable.php', get_option('active_plugins') ) ) {
				echo 'Blog ID: ' . $site_id;
				echo ' --- Total: ' . do_shortcode('[charitable_stat display=total]');
				echo ' --- Donors: ' . do_shortcode('[charitable_stat display=donors]');
				echo ' --- Campaigns: ' . wp_count_posts( 'campaign' )->publish;
				echo '<br>';	
			}
		}
		restore_current_blog();
	}	
	
	return ob_get_clean();
} );
```
