### ISSUE TITLE
a Changelog would be great ;-)

### ISSUE THREAD

**Issue by altatof** [Charitable/Charitable#92]

**Comment by rafecolton** [comment]
There is a currently a changelog in [readme.txt](https://github.com/Charitable/Charitable/blob/master/readme.txt#L111-L202), which can be found at the top level of the project

**Comment by altatof** [comment]
sorry i looked at the readme but did not go far enough to find it; maybe it would be better to put it in a separate Changelog file ? anyway i am gonna read it now; thanks :)

**Comment by ericnicolaas** [comment]
Yes, there is a Changelog in the readme.txt, which is where the changelog on wordpress.org/plugins/charitable/ comes from. Not really in favour of duplicating it elsewhere.
